### ISSUE TITLE
Help for routes_training.xml

### ISSUE THREAD

**Issue by leeaccy** [carla-simulator/scenario_runner#1043]
Hi, everybody,

I tried scenario_runner 0.9.15, very nice and amazing! 
Can anyone provide routes_training.xml for Towns other than Town 12 in scenario_runner 0.9.15. I found routes_training.xml in scenario_runner 0.9.15 only provide routes for Town 12.

**Comment by PabloVD** [comment]
Hi, thanks for your question. Scenario runner only provides routes for Town12 as training routes (`routes_training.xml`), and for Town13 as validation routes (`routes_validation.xml`). Note that there is also a `routes_devtest.xml` with two Town12 routes just for debugging, and `routes_town10.xml` with one route in Town10, for trying the leaderboard without loading the Town12.
