### ISSUE TITLE
Wrong behavior in object_crash_vehicle scenario

### ISSUE THREAD

**Issue by germanros1987** [carla-simulator/scenario_runner#106]
We have detected an error in object_crash_vehicle

The reference to derive the location of the adversaries is obtained via self.ego_vehicle. 

```
lane_width = self._reference_waypoint.lane_width
location, _ = get_location_in_distance(self.ego_vehicle, _start_distance)
waypoint = self._wmap.get_waypoint(location)
```

However, this is incorrect for all those cases where the ego_vehicle is still far away from the scenario. The correct object would be config.ego_vehicle, which despite its horribly misleading name refers to the trigger position of the scenario.

I would advise to:

 * Change the parser to assign the right name to this field, i.e., scenario_trigger_location
* Fix this behavior

**Comment by fabianoboril** [comment]
The name is not horribly wrong. It is designed to reflect the ego vehicle spawn location. We started to abuse the parser for things it was never designed to. Maybe we should more think about that, rather then just changing names...

**Comment by fabianoboril** [comment]
Closed, as PR is merged.
