### ISSUE TITLE
NotimplementedError("negative target speeds are not yet supported")

### ISSUE THREAD

**Issue by PhyllisJi** [carla-simulator/scenario_runner#1070]
**Describe our question or idea**
Simulation of vehicle reversing in carla. 
```xml
<PrivateAction>
 <LongitudinalAction>
  <SpeedAction>
   <SpeedActionDynamics dynamicsShape="linear" value="1.5" dynamicsDimension="time"/>
   <SpeedActionTarget>
    <RelativeTargetSpeed value="-5" entityRef="hero" continuous="true" speedTargetValueType="delta"/>
   </SpeedActionTarget>
  </SpeedAction>
 </LongitudinalAction>
</PrivateAction>
```

**Expected behavior**
Simulation of vehicle reversing in carla. 

**Current behavior**
NotimplementedError("negative target speeds are not yet supported")

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04
 - CARLA Version CARLA 0.9.14
 - Python version 3.6.9
 - Version 0.9.13

**Comment by glopezdiest** [comment]
Hello @PhyllisJi, not all OpenScenario actions are currently supported, and the negative speed action is one of those, as shown by the NotImplementedError. The detailed docs about them can be found [here](https://scenario-runner.readthedocs.io/en/latest/openscenario_support/).

We also encourage anyone who wants to help to feel free to implement them and do a PR with them. It doesn't have to be all of them, even just one action will be highly appreciated
