### ISSUE TITLE
Config broken

### ISSUE THREAD

**Issue by kristjard** [carla-simulator/scenario_runner#1072]
**Describe the bug**
Merge conflict text in last merge, file: [scenario_runner](https://github.com/carla-simulator/scenario_runner/tree/master)/[srunner](https://github.com/carla-simulator/scenario_runner/tree/master/srunner)/[scenarioconfigs](https://github.com/carla-simulator/scenario_runner/tree/master/srunner/scenarioconfigs)
/osc2_scenario_configuration.py

lines 22-29 and 166-169.

**To Reproduce**
Pull master and try to run a scenario

**Expected behavior**
Scenario will run

**Screenshots**
![image](https://github.com/carla-simulator/scenario_runner/assets/47303017/de17112f-f092-4ea1-9808-499cc4328761)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - CARLA Version [CARLA 0.9.15]
 - Python version [3.8]
 - Version [master]

**Additional context**
Also left a comment on the MR but it's already merged :)
Have a look @XiaoFei9704

**Comment by PabloVD** [comment]
Thanks for noticing it, it has already been fixed in the last commit.
