### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by ljj88** [carla-simulator/scenario_runner#1073]
**Describe our question or idea**
hello, when i call the API `carla.client.show_recorder_file_info(recorder_name)` to print the info of the log file, it reminds me the error info.
![screenshot](https://github.com/carla-simulator/scenario_runner/assets/74171252/729065e3-ed6f-4998-96f0-6f98cde582bd)

Before I use the function, there are `carla.client.start_recorder(recorder_name)` and `carla.client.stop_recorder()` have already been called. 

I followed the guide to passed in a string parameter.
![image](https://github.com/carla-simulator/scenario_runner/assets/74171252/4ed596b1-a70f-4724-8dfc-3bd3eee98efb)

**Expected behavior**
Are there any environmental configuration requirements before calling this parameter? Can someone help me？

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CARLA Version [e.g. CARLA 0.9.15]
 - Python version [e.g. 3.8]
 - Version [e.g. 0.9.15]

**Comment by glopezdiest** [comment]
Hello @ljj88, the `show_recorder_file_info` requires an additional argument, the `show_all` flag

![image](https://github.com/carla-simulator/scenario_runner/assets/58212725/4a3759f9-fa2b-4e03-986a-90c7ee033f4b)

so you should have the issue resolved with 
```py
print(self.client.show_recorder_file_info(recorder_name, False))
```

Closing the issue, but feel free to reopen it if that doesn't solve it
