### ISSUE TITLE
OSC2ScenarioConfiguration' object has no attribute 'route' 

### ISSUE THREAD

**Issue by zwhaa** [carla-simulator/scenario_runner#1088]
When I run the python scenario_runner.py --openscenario2 srunner/examples/xxx.osc command, no matter which file I run, I will report an error：OSC2ScenarioConfiguration' object has no attribute 'route' 'OSC2ScenarioConfiguration' object has no attribute 'route' No more scenarios .... Exiting

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - CARLA Version [e.g. CARLA 0.9.15]
 - Python version [e.g. 3.7]
 - Version [e.g. 0.9.15]

**Comment by glopezdiest** [comment]
Hey @zwhaa please check if you have [this line](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenarioconfigs/openscenario_configuration.py#L37) in your code, as it is the one that fixes the issue. It was part of the 0.9.15 release though, so not sure why you wouldn't have it.

Feel free to reopen the issue if it is still happening

**Comment by zwhaa** [comment]
Hey @glopezdiest This line of code is included in the code. I tried to add the following content to the osc2scenariounconfiguration. py file according to the error prompt, and it ran without any problems.

**Comment by hsiang-lee** [comment]
https://osc2studio.online
