### ISSUE TITLE
Issues with using scenario_runner.py for versions 0.9.15

### ISSUE THREAD

**Issue by NayaBaslan** [carla-simulator/scenario_runner#1120]
**Version 0.9.15 for scenario_runner not working**
I have CARLA 0.9.15 running and I need to use scenario_runner. According to the instructions in this repo, I need to install the corresponding version of scenario_runner: Version 0.9.15
To run CARLA:
`./CarlaUE4.sh` 
and the scenario_runner:
`python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld`

However `scenario_runner.py` is not working and giving the errors:
` from agents.navigation.global_route_planner import GlobalRoutePlanner
ModuleNotFoundError: No module named 'agents' `

**Desktop**
 - OS: [Ubuntu 20.04]
 - CARLA Version [ CARLA 0.9.15]
 - Python version [3.8.10 ]
 - Version [0.9.15]

Can someone please help me on this?
As if the path to carla is not regognized, but the instructions for this are only for building from source.
It should directly work when downloading from packages.

**Comment by NayaBaslan** [comment]
however, when I try the `python3 no_rendering_mode.py` from scenario_runner, it works well and it connected to CARLA.
So the issue only seems for the agents. 

On the other hand, when I use a basic or behavior agent directly in the CARLA directory, for example in the `automatic_contol.py` script in CARLA, it works without problems.

I face the issue only when running ` python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld `

**Comment by NayaBaslan** [comment]
solved by copying agents directory into scenario_runner directory.

**Comment by NayaBaslan** [comment]
solved by copying agents directory into scenario_runner directory.

**Comment by minhaj6** [comment]
Simplest solution. This should be in the docs. 👍🏻

**Comment by HuangChiEn** [comment]
wow, v0.9.15, the latest released version, even have this kind of mistake ?!
placing dir to the wrong place ?!
