### ISSUE TITLE
set velocity in scenatio runner

### ISSUE THREAD

**Issue by dyli96** [carla-simulator/scenario_runner#151]
Hi,

Is it possible to set velocity under autopilot in scenario runner?
I also would like to get the velocity data through the scenario in sample time interval of the vehicles and actors, is that possible?

Thanks a lot!

**Comment by fabianoboril** [comment]
You can use the BasicAgent behavior instead of the autopilot. Then you can set a target velocity.

**Comment by HarnarayanSingh** [comment]
> Hi,
> 
> Is it possible to set velocity under autopilot in scenario runner?
> I also would like to get the velocity data through the scenario in sample time interval of the vehicles and actors, is that possible?
> 
> Thanks a lot!

Hey!
Were you able to sort this issue?
