### ISSUE TITLE
failed to get world settings

### ISSUE THREAD

**Issue by hakuturu583** [carla-simulator/scenario_runner#174]
I test carla with scenario_runner, but I found some problems.
When I try 

```
python3 scenario_runner.py --scenario MasterScenario
```

it failed because of 

```
AttributeError: 'World' object has no attribute 'get_settings'
```

it happens in all scenarios

![Screenshot from 2019-04-09 22-11-06](https://user-images.githubusercontent.com/10348912/55804504-5a5e0f80-5b17-11e9-9305-ec655dc41f04.png)

**Comment by fabianoboril** [comment]
Hi,

the master scenario is not designed for standalone execution. In addition, you need to use CARLA 0.9.5 or switch to the master branch.

**Comment by hakuturu583** [comment]
@fabianoboril Other scenario has also same errors.

**Comment by fabianoboril** [comment]
@hakuturu583 As said, you need to update your CARLA. In preparation of the challenge we had to modify various things on both sides. As a result, if you do not use the **master** branch of the scenario_runner, you have to use the **master** branch of CARLA.

**Comment by vivekjaiswal003** [comment]
I am using the latest version of Carla 0.9.5 but still this issue persist. In manual_control.py, I made the following changes 
    world = World(client.get_world(), hud, args.filter, args.rolename)
    settings = world.get_settings()
    settings.synchronous_mode = True
    world.apply_settings(settings)

 AttributeError: 'World' object has no attribute 'get_settings' 

How to resolve this issue?

**Comment by glopezdiest** [comment]
Closing this, as this is no longer the case. If this can be reproduced by current Scenario Runner, feel free to reopen it
