### ISSUE TITLE
Failed to localize before lane change

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/scenario_runner#238]
Hi,

Using the scenario runner, I wrote a lane merge scenario class to execute other vehicle merging into the ego vehicle lane
I wrote a script where other_actor merges with ego vehicle lane after moving ahead using BasicAgent class. It shows a warning 

> failed to Localize!: 54 -3
 
Could you explain why this happens before lane change over?

Also, a general question. Why do we always get this "resetting ego-vehicle" message on the screen?

Thanks,
Deepak

**Comment by Derekabc** [comment]
Hi, any update to this question?  Where can i find the lane merge algorithm? Thanks

**Comment by deepakreddy63** [comment]
Hi,
@Derekabc .. I developed it using BasicAgent with setdestination.
This failed to localize issue happens when there is some issue with _localize function in global_route_planner.py script.

I'm closing this issue.Thanks.
