### ISSUE TITLE
Update config parser

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/scenario_runner#247]
https://github.com/carla-simulator/scenario_runner/blob/c7210f4bbe0520d0e99092f4d8390519b090decf/srunner/tools/config_parser.py#L219

This line should be 
```
if set_attrib(scenario, 'type', None) == scenario_name:
```
Otherwise, [the agent from your example](https://carlachallenge.org/get-started/) is not working with latest xml definitions in branch `carla-challenge`

**Comment by fabianoboril** [comment]
Should be fixed in current master. Please re-open, if the problem still exists.
