### ISSUE TITLE
Scenario Loads & Runs but ego vehicle does not move. Condition not satisifed

### ISSUE THREAD

**Issue by f5maki** [carla-simulator/scenario_runner#28]
Am I missing something?
Carla 9.2,  Town 03,  Scenario  - OppositeVehicleRunningRedLight

Scenario loads and starts fine. Vehicles spawn etc.
Ego vehicle has no velocity, so other vehicle does not move and jump the red light. 
Is there a key press to start the scenario or are you expecting to interface to a real AV or AV model that provides a velocity?

**Comment by fabianoboril** [comment]
Start the manual_control.py that comes with the scenario_runner and use the arrow-keys on your keyboard to make to vehicle move.

**Comment by f5maki** [comment]
Ah!! Thanks!! Nice scenario btw.
