### ISSUE TITLE
scenario_runner.py: IndexError: blueprint 'sensor.other.lane_detector' not found

### ISSUE THREAD

**Issue by ADulian** [carla-simulator/scenario_runner#287]
Hello,

Just trying to run the latest master branch of scenario_runner and I get the following error message: 
"""
...
IndexError: blueprint 'sensor.other.lane_detector' not found
blueprint 'sensor.other.lane_detector' not found
No more scenarios .... Exiting
"""

Currently using carla 0.9.5. Any suggestion how to fix it?

Cheers

**Comment by fabianoboril** [comment]
With CARLA 0.9.5 the name of this sensor has changed. You may want to switch to the development branch for now, or change the name to lane_invasion instead of lane_detector.

**Comment by fabianoboril** [comment]
There is now a new release for scenario_runner to support 0.9.5. Also  the master branch was updated. This should fix this issue.
