### ISSUE TITLE
Update the Getting Started documentation?

### ISSUE THREAD

**Issue by talsperre** [carla-simulator/scenario_runner#295]
As scenario runner now supports 0.9.5, the Getting Started file should also be updated to reflect the changes required. I needed to add `${CARLA_ROOT}/PythonAPI/carla/agents/` to the `PYTHONPATH` to make it work. 

Also, the scenario's now need to be called differently as the XML files have been updated I suppose. 
Earlier `python scenario_runner.py --scenario FollowLeadingVehicle` used to work but now I had to use `python scenario_runner.py --scenario FollowLeadingVehicle_1`.

**Comment by fabianoboril** [comment]
Thank you for the hints. I just created a PR #296 to address the documentation.
