### ISSUE TITLE
Can't run Scenario_runner

### ISSUE THREAD

**Issue by dongyy1148** [carla-simulator/scenario_runner#299]
OS: Ubuntu 16.04
Python: 3.5
I'm trying to run the : python scenario_runner.py
The problem is showed below. I use Carla 0.8.4 and newest py_trees packgae.
![image](https://user-images.githubusercontent.com/43221681/59636375-5bb44580-9121-11e9-9f72-b8850a33bd11.png)

**Comment by dongyy1148** [comment]
If I use python 2,7 to run the file, it will give me the result like
![image](https://user-images.githubusercontent.com/43221681/59638060-5527cd00-9125-11e9-9246-0aa92e6d4d98.png)
Could you help figure it out? Thanks!

**Comment by fabianoboril** [comment]
Hi,

It seems you use an old CARLA version. For the scenario runner you need to use at least version 0.9.2, for the current version of the scenario runner even version 0.9.5 is required.

Regarding the Python 3.5 issue: It seems your py_tree installation has some issues. I recommend to install version 0.8.2 via pip, as described in the documentation.

**Comment by dongzh1148** [comment]
Thanks a lot! I will try to implement with the latest version today!

**Comment by fabianoboril** [comment]
I assume the problem was resolved. Please re-open the issue, if you still face issues.
