### ISSUE TITLE
Problem with repeated use of waypointFollower behavior 

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/scenario_runner#302]
Hi,

In "FollowLeadingVehicleWithObstacle" class, the WaypointFollower atomic behavior is used in two instances for same actor which causes the problem of vehicle looping back

> stop_near_intersection.add_child(WaypointFollower(self.other_actors[0], 35))
        stop_near_intersection.add_child(InTriggerDistanceToNextIntersection(self.other_actors[0], 20))
>        driving_to_next_intersection.add_child(WaypointFollower(self.other_actors[0], self._first_actor_speed))
        driving_to_next_intersection.add_child(InTriggerDistanceToVehicle(self.other_actors[1],
                                                                          self.other_actors[0], 15))

**Comment by deepakreddy63** [comment]
Hi,

I tried to correct this by making minor changes in WaypointFollower behavior.

![WPFollwer](https://user-images.githubusercontent.com/28020109/60051360-d12f9100-96a0-11e9-9268-b2d9f4596559.png)

I commented the setup function code and updated the waypoint list at the first update tick to get the latest waypoint list at current vehicle position.

**Comment by krdindorkar19** [comment]
Hi @deepakreddy63 ,
I am also facing the same issue, you problem has been solved?

**Comment by fabianoboril** [comment]
@deepakreddy63 @krdindorkar19 I just created a PR and a fix/waypointFollower branch. Please give it a try and let me know if it fixes the described issues.

**Comment by krdindorkar19** [comment]
@fabianoboril Yes, it has been solved. Thank you !

**Comment by fabianoboril** [comment]
@deepakreddy63 Your changes should not change the behavior,

**Comment by deepakreddy63** [comment]
@fabianoboril  Yes, it works. Thanks !
