### ISSUE TITLE
How to return the timestamp with the returned values

### ISSUE THREAD

**Issue by Dola47** [carla-simulator/scenario_runner#304]
Dear All,

I modified the KeepVelocity class to save the values of the location, acceleration, velocities of the 2 cars in NoSignalJunctionScenario. However, I want to return the values accompanied with the timestamp where these values occurred. 

Any ideas how to do that.

Thanks.

**Comment by fabianoboril** [comment]
You could use a py_trees blackboard or add a pure static class with static getters and setters. I would recommend using a blackboard, as it is the cleaner way :)

Here is a link with additional info on py_trees blackboards:
https://py-trees.readthedocs.io/en/devel/blackboards.html
