### ISSUE TITLE
The scenario cannot be loaded?

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/scenario_runner#311]
Hello.
when I run `python scenario_runner.py --scenario FollowLeadingVehicle_1`,I receive the following message:
`Preparing scenario: FollowLeadingVehicle_1
The scenario cannot be loaded
global name 'LocalPlanner' is not defined
No more scenarios .... Exiting
`
How I should solved it?

**Comment by fabianoboril** [comment]
You need to setup the PYTHONPATH as described in the getting_started documentation.

**Comment by JackRen88** [comment]
Hello, @fabianoboril .

Firstly,I setup the PYTHONPATH `(export PYTHONPATH=$PYTHONPATH:/home/rcj/carla_0.9.5/PythonAPI/carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg:/home/rcj/carla_0.9.5/PythonAPI/carla/agents:/home/rcj/carla_0.9.5/PythonAPI)` in the .bashrc,when I run `python scenario_runner.py --scenario FollowLeadingVehicle_1`,I receive the following message:
`Traceback (most recent call last):
  File "scenario_runner.py", line 27, in <module>
    from srunner.scenarios.background_activity import *
  File "/home/rcj/scenario_runner-0.9.5/srunner/scenarios/background_activity.py", line 13, in <module>
    from srunner.scenariomanager.atomic_scenario_behavior import *
  File "/home/rcj/scenario_runner-0.9.5/srunner/scenariomanager/atomic_scenario_behavior.py", line 30, in <module>
    from srunner.tools.scenario_helper import detect_lane_obstacle, get_distance_along_route
  File "/home/rcj/scenario_runner-0.9.5/srunner/tools/scenario_helper.py", line 20, in <module>
    from agents.tools.misc import vector
ImportError: No module named agents.tools.misc
`
Therefore,I try to use the scripy(setup_environment.sh) that is in the scenario_runner to setup PYTHONPATH ,I get the message:
`Preparing scenario: FollowLeadingVehicle_1
The scenario cannot be loaded
global name 'LocalPlanner' is not defined
No more scenarios .... Exiting
`
How I should solved it? This problem has been bothering me for several days.

**Comment by fabianoboril** [comment]
Please see the change in PR #318. This should resolve your issue. The PYTHONPATH was incomplete.

**Comment by JackRen88** [comment]
Hello, @fabianoboril 
Thanks for your reply!
could you provide the complete path?

**Comment by fabianoboril** [comment]
Which problem? The localplanner or the tools.misc is not found?

**Comment by JackRen88** [comment]
The problem is that when I  include CARLA Python API to the Python path:
`export PYTHONPATH=$PYTHONPATH:/home/rcj/carla_0.9.5/PythonAPI/carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg:/home/rcj/carla_0.9.5/PythonAPI/carla/agents:/home/rcj/carla_0.9.5/PythonAPI/carla`
I get the message:
`Preparing scenario: FollowLeadingVehicle_1 The scenario cannot be loaded global name 'LocalPlanner' is not defined No more scenarios .... Exiting`

**Comment by fabianoboril** [comment]
Try the following:
`export CARLA_ROOT=/home/rcj/carla_0.9.5
 export PYTHONPATH=${CARLA_ROOT}/PythonAPI/carla:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.5-py2.7-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents`
Then run Python (Python 2.7 in this case) and run:
`from agents.navigation.local_planner import LocalPlanner`

Does this work?

**Comment by JackRen88** [comment]
@fabianoboril 。
I don't understand your instructions.
I look at the scenario_runner.py file,find that exception is 
`try:
                    CarlaActorPool.set_world(self.world)
                    self.prepare_ego_vehicle(config)
                    scenario = scenario_class(self.world,
                                              self.ego_vehicle,
                                              config,
                                              args.randomize,
                                              args.debug)
                except Exception as exception:
                    print("The scenario cannot be loaded")
                    if args.debug:
                        traceback.print_exc()
                    print(exception)
                    self.cleanup()
                    continue`
Please help me find where the problem is.

**Comment by fabianoboril** [comment]
Well for some reason, your python environment is not complete. Therefore, please run the steps I posted above (just one after the other...), such that we can try to understand where the problem is exactly.

**Comment by JackRen88** [comment]
@fabianoboril.
According to your  instruction.
I run the following step:

**Comment by fabianoboril** [comment]
Using the same export commands, can you try to run the scenario?

**Comment by JackRen88** [comment]
Hello,@fabianoboril .
I can't run the scenario.

`rcj@rcj-OMEN-by-HP-Laptop-15-ce0xx:~/scenario_runner-0.9.5$ python scenario_runner.py --scenario FollowLeadingVehicle_1
Preparing scenario: FollowLeadingVehicle_1
The scenario cannot be loaded
global name 'LocalPlanner' is not defined
No more scenarios .... Exiting`

**Comment by fabianoboril** [comment]
Can you please run with "--debug". Then we will see the full exception. Something seems wrong with the import for your setup.

**Comment by fabianoboril** [comment]
I assume the issue was resolved as there was no further input. Please re-open if it still exists.

**Comment by laks1806** [comment]
@fabianoboril, I tried changing the path and everything seems correct but this error keeps coming : 
```
python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld
Configuration for scenario FollowLeadingVehicle_1 cannot be found!
No more scenarios .... Exiting
```
my python path is: 
`/opt/carla-simulator/PythonAPI/carla/dist/carla-0.9.11-py2.7-linux-x86_64.egg:/opt/carla-simulator/PythonAPI/carla/agents:/opt/carla-simulator/PythonAPI/carla`
