### ISSUE TITLE
Problems with Documentation for challenge evaluation

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/scenario_runner#319]
Hi,

I was trying to run challenge evaluation looking at the documentation and found problems with documentation.

Could you please update the documentation as to how to get started. Example is:
python3 srunner/challenge/challenge_evaluator.py --list

This throws file not found error and same errors for remaining commands as well.

Thanks. 

Deepak

P.S: I could learn a lot from Carla and my sincerest thanks to the whole Carla Team.

**Comment by fabianoboril** [comment]
Documentation was updated in PR #318
