### ISSUE TITLE
Not expected result when running challenge_evaluation

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/scenario_runner#323]
Hi,
I started the Carla server both with no editor. Later, I also tried with the unreal editor.
Then, I tried running as per the documentation,
python srunner/challenge/challenge_evaluator_routes.py --scenarios=${ROOT_SCENARIO_RUNNER}/srunner/challenge/all_towns_traffic_scenarios1_3_4.json --agent=${ROOT_SCENARIO_RUNNER}/srunner/challenge/autoagents/DummyAgent.py

and saw no output from sensors in the terminal.
I checked the results.json file and below is the image of sample part of file.
I understood that the error is due to Carla simulator not responding. But then it responds when I run normal scenario_runner.py scenario to verify the problem.

![challenge_ev_error](https://user-images.githubusercontent.com/28020109/61004955-2de3aa80-a335-11e9-8726-28c13124fed3.png)

I'm not sure what might be the problem. Is it possible to try with a new file with a small number of scenarios?

I tried with HumanAgent and a blank pygame window pops up and vanishes and same thing repeats.

Thanks,
Deepak

**Comment by fabianoboril** [comment]
Which version of CARLA and the scenario runner do you use?

**Comment by deepakreddy63** [comment]
I use 0.9.5 Carla version and 0.9.5 scenario runner (latest with git pull).

**Comment by fabianoboril** [comment]
Attention: If you are on master branch and do a git pull, you have a version that does no longer work with CARLA 0.9.5. This is already a preparation for the upcoming CARLA 0.9.6. Please checkout the version v0.9.5.1. This should work with CARLA 0.9.5. I just updated the documentation to clarify this point.

**Comment by deepakreddy63** [comment]
Hi,

Thanks for the reply.
I tried switching to carla_challenge branch and seemed to work fine in one system.

when I tried in another system it gives time out error.
![CHAL](https://user-images.githubusercontent.com/28020109/61089567-85534a80-a409-11e9-8efa-53967fe01181.png)

Any idea as to why this is happening?

Thanks,
Deepak

**Comment by fabianoboril** [comment]
Hi,
you don't need to switch to the old challenge branch. Just go back to the tagged version v0.9.5.1. This should work with CARLA 0.9.5. 

Sometime you can get timeout failures. This depends a bit on the system performance on how responsive CARLA is on this system.

**Comment by deepakreddy63** [comment]
HI @fabianoboril ,

I switched to tagged version v0.9.5.1 and tried the script.
I get the following errors for dummy agent where it says wheel doesn't have attribute steer_angle.

![Carla_challenge1](https://user-images.githubusercontent.com/28020109/61329134-9e357480-a7ea-11e9-87ee-ded045f37ba1.png)

The pygame window appears and dissapear  for HumanAgent
![carla_challenge2](https://user-images.githubusercontent.com/28020109/61329257-e359a680-a7ea-11e9-9ff9-ae0584861219.png)


It shows same error for carla_challenge branch for DummyAgent, but HumanAgent works though.

Thanks

**Comment by fabianoboril** [comment]
Then you use a CARLA version that is newer than 0.9.5. At some point steer_angle became max_steer_angle...

**Comment by deepakreddy63** [comment]
Hi,
I tries with v0.9.6 of both scenario_runner and carla to run challenge_evaluator_routes.py script. 

Just a small correction. 
There is no input for "rolename" parameter in request_new_actor function inside "prepare_ego_vehicle" function of challenge_evaluator_routes.py file and this causes the ego_vehicle to not move when NPCAgent is used as it cannot find rolename attribute for ego actor in NPCAgent script.

**Comment by fabianoboril** [comment]
Could you please test PR #345? I just fixed this issue...

**Comment by deepakreddy63** [comment]
The fix works and ego vehicle is now moving.

But I noticed a few more issues when ego vehicle moves.
1) Scenario 3 doesn't spawn human actor
2) Ego vehicle abruptly stops at [34.99] of route1 in town 02

Not sure what is happening

**Comment by lijecaru** [comment]
@deepakreddy63  how did you try the fix? I'm also testing NPC agent but it doesn't move and I don't find where to modify it. Thank you.

**Comment by fabianoboril** [comment]
@deepakreddy63: Please see PR #346. This should fix the first problem.

**Comment by deepakreddy63** [comment]
@fabianoboril 
Thansk for the fix. The second problem also seems to be having the same correction as first one where the InTriggerDistanceToLocationAlongRoute is not triggered as it is taking self.other_actors[0].get_location() as input instead of self._other_actor_transform.location.

**Comment by fabianoboril** [comment]
Oh yes. Fix is on its way.

**Comment by fabianoboril** [comment]
PR #347 addresses TS04. Please let me know, if it helps.

**Comment by deepakreddy63** [comment]
Hi @fabianoboril ,

A small correction.
In PR 347, it is changed as self._other_actor_transform instead of self._other_actor_transform.location.

**Comment by fabianoboril** [comment]
Fix will be released soon.
