### ISSUE TITLE
ByValue SimulationTime conditions with the given specification is not yet supported

### ISSUE THREAD

**Issue by jS5t3r** [carla-simulator/scenario_runner#327]
I have written a scenario where the Ego vehicle should start driving when I start the simulation. 

```
➜  scenario_runner git:(3b72dc3) ✗ python scenario_runner.py --openscenario srunner/configs/avenue/EgoStraight.xosc --reloadWorld
Preparing scenario: EgoStraight
The scenario cannot be loaded
ByValue SimulationTime conditions with the given specification is not yet supported
```
The start condition looks like this: 

```
<Start>
    <ConditionGroup>
        <Condition name="StartCondition" delay="0" edge="rising">
            <ByValue>
                <SimulationTime value="0" rule="equal_to"/>
            </ByValue>
        </Condition>
    </ConditionGroup>
</Start>
```

Can you tell me a different start condition so that the ego vehicle starts from the beginning? The reason for that is that I can  regulate the velocity of the vehicle.  I don't know how to change the velocity in the manual_control.py.

**Comment by fabianoboril** [comment]
As discussed via discord, a workaround is to use a distance. Are you working on the SimulationTime condition? If not, I could take a look.
