### ISSUE TITLE
OpenScenario Pedestrian Support

### ISSUE THREAD

**Issue by jS5t3r** [carla-simulator/scenario_runner#329]
I saw that pedestrians are not supported in regard to OpenScenario. I would like to spawn Pedestrians at a certain position and give them actions such as walking over the crosswalk.

I am in the hope that it is only expanding the  wrapper of the scenario_runner. I am grateful for every support.

I am going to work on that to expand this functionality on CARLA 0.9.6.

**Comment by fabianoboril** [comment]
I created a first PR including a simple example based on your discord proposal. Please have a look and let me know if it works.

**Comment by jS5t3r** [comment]
It works so far :)
