### ISSUE TITLE
Configuration for scenario cannot be found

### ISSUE THREAD

**Issue by lijecaru** [carla-simulator/scenario_runner#338]
I am testing Carla0.9.6 and its corresponding scenario_runner. After following the instructions  [here](https://github.com/carla-simulator/scenario_runner/blob/development/Docs/getting_started.md/#install_prerequisites) I want to launch the follow vehicle example and I get the following:
```
$ python scenario_runner.py --scenario FollowLeadingVehicle
Configuration for scenario FollowLeadingVehicle cannot be found!
```
My environment variables are in my .bashrc, as follows:
```
export CARLA_ROOT=/home/user/Carla0.9.6/carla0.9.6
export CARLA_SERVER=/home/user/Carla0.9.6/carla0.9.6/CarlaUE4.sh
export ROOT_SCENARIO_RUNNER=/home/user/Carla0.9.6/scenario_runner0.9.6
export PYTHONPATH=$PYTHONPATH:/home/user/Carla0.9.6/carla0.9.6/PythonAPI/carla/dist/carla-0.9.6-py2.7-linux-x86_64.egg:/home/user/Carla0.9.6/carla0.9.6/PythonAPI/carla
```

**Comment by fabianoboril** [comment]
Hi,

please check our current master branch. There the documentation has changed a bit. The scenario name changed to FollowLeadingVehicle_1

https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_started.md
