### ISSUE TITLE
Failure when loading scenario with scenario_runner.py

### ISSUE THREAD

**Issue by powerfulwang** [carla-simulator/scenario_runner#354]
I'm following the instructions of https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_started.md, and get failure when using scenario_runner.py. 

I'm using CARLA 0.9.6 and scenarion_runner 0.9.6. After adding 
```
export CARLA_ROOT=/home/user/CARLA_0.9.6
export CARLA_SERVER=/home/user/CARLA_0.9.6/CarlaUE4.sh
export ROOT_SCENARIO_RUNNER=/home/user/CARLA_0.9.6/scenario_runner
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.6-py2.7-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla
```
to .bashrc file, I got
> $ python scenario_runner.py  --scenario FollowLeadingVehicle_1 --reloadWorld
Preparing scenario: FollowLeadingVehicle_1
ScenarioManager: Running scenario FollowVehicle
Failure!
ERROR: failed to destroy actor 391 : unable to destroy actor: not found 
No more scenarios .... Exiting
No more scenarios .... Exiting

and other scenarios are also failed, for example, 
> $ python scenario_runner.py  --scenario OtherLeadingVehicle_1 --reloadWorld --output
Preparing scenario: OtherLeadingVehicle_1
ScenarioManager: Running scenario VehicleDeceleratingInMultiLaneSetUp
Scenario: VehicleDeceleratingInMultiLaneSetUp --- Result: TIMEOUT
Start time: 2019-08-19 21:52:49
End time: 2019-08-19 21:53:21
Duration: System Time 31.53s --- Game Time 80.05s
Ego vehicle:  Actor(id=213, type=vehicle.lincoln.mkz2017)
Other actors: Actor(id=214, type=vehicle.nissan.patrol); Actor(id=215, type=vehicle.audi.tt); 

                Actor             |            Criterion           |   Result    | Actual Value | Expected Value 
         lincoln.mkz2017 (id=213) |         CheckCollisions (Req.) |     SUCCESS |         0.00 |         0.00 
                                  |                       Duration |     FAILURE |        80.05 |        80.00 
> Failure!
No more scenarios .... Exiting
No more scenarios .... Exiting

**Desktop:**
 - OS: Ubuntu 16.04
 - CARLA Version: CARLA 0.9.6
 - Python version: 2.7 & 3.5
 - Version: 0.9.6

**Comment by ruminahui** [comment]
Hi @powerfulwang,
Did you managed to solved this issue? If so, can you provide some details on what was causing it?
