### ISSUE TITLE
Error with Scenario_4

### ISSUE THREAD

**Issue by deepakreddy63** [carla-simulator/scenario_runner#355]
**Question**

Problem with the repeated running of the same scenario_4. The scenario is running some times and gives the following error most of the times. 
I get the below error
frame == _episode->GetState()->GetTimestamp().frame
I recently upgraded to CARLA 0.9.6

**Screenshot**
![Screenshot from 2019-08-19 16-41-21](https://user-images.githubusercontent.com/28020109/63297801-3a4a1400-c2a0-11e9-872d-b108921e7538.png)

**Expected behavior**
Scenario4 should execute each time correctly

**Desktop**
 - OS: Ubuntu 16.04
 - CARLA Version  CARLA 0.9.6
 - Python version  3.6
 - Version 0.9.6

**Comment by fabianoboril** [comment]
A fix is in preparation. I found this issue myself just a few days ago.
