### ISSUE TITLE
Improve logical compliance with OpenSCENARIO intent

### ISSUE THREAD

**Issue by matthewcoyle-cpc** [carla-simulator/scenario_runner#365]
**Description**
The current behaviour tree interpretation of OpenSCENARIO executes acts, maneuvers and events sequentially as well as ignoring ConditionGroups

**Expected behavior**
Acts, Maneuvers and Events should occur in parallel
ConditionGroups should be used to group conditions to allow for logical ORs

**Comment by matthewcoyle-cpc** [comment]
@fabianoboril I've made the changes on my forked branch https://github.com/matthewcoyle-cpc/scenario_runner/tree/openscenario_logic
Unfortunately I'm still in the position where I can't test the changes at all

**Comment by fabianoboril** [comment]
@matthewcoyle-cpc: Can you rebase on the current master branch and open a PR? I will test your changes in parallel, and then we could start bringing in the first set of new OpenSCENARIO features 👍
