### ISSUE TITLE
Missing path in Getting Started documentation

### ISSUE THREAD

**Issue by vangelis-tri** [carla-simulator/scenario_runner#38]
It appears that with the release of Carla 0.9.3 in the Getting Started documentation the following needs to be added to PYTHONPATH:

${CARLA_ROOT}/PythonAPI/agents/navigation

Also, it would be good to explicitly add to the instructions the step to pip install networkx .

**Comment by fabianoboril** [comment]
I think this should go to CARLA directly, as networkx is a requirement for the CARLA agents. I add @nsubiron in the loop for this.

**Comment by fabianoboril** [comment]
Updated the documentation. Should be correct now.
