### ISSUE TITLE
NoSignalJunctionCrossing not reporting - (it has timeout=0)

### ISSUE THREAD

**Issue by chauvinSimon** [carla-simulator/scenario_runner#392]
I am testing my own agent derived from `BasicAgent `on **`NoSignalJunctionCrossing`**.

I cannot understand why no report is generated, despite the `--file` flag. For instance, `FollowLeader*`, `SignalizedJunction*`, `OppositeVehicleRunning*` all generate a report.

`NoSignalJunctionCrossing` has a `end_condition` based on `InTriggerRegion`.
**My car does arrive in this region**.

So the only reason I can think of is the *timeout*.
I have noticed that **`NoSignalJunctionCrossing` is the only scenario to have `timeout=0` as default**.
Could that be a problem?

(Working with CARLA 0.9.6 on ubuntu).

**Comment by glopezdiest** [comment]
I know this is a little late, and I am sorry for that, but indeed, there was a bug with this scenario. It wasn't related to the timeout though, but to the *criteria_enable* variable instead, which wasn't properly set. This is fixed now
