### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'rolename'

### ISSUE THREAD

**Issue by leomark138148168** [carla-simulator/scenario_runner#398]
**Describe our question or idea**
When I ran

> python srunner/challenge/challenge_evaluator_routes.py --scenarios=srunner/challenge/all_towns_traffic_scenarios1_3_4.json --agent=srunner/challenge/autoagents/DummyAgent.py

it told me that

> WARNING: attempting to destroy an actor that is already dead: Actor 213 (vehicle.lincoln.mkz2017)...

after adding

> --debug=1

it told me that

> TypeError: __init__() missing 1 required positional argument: 'rolename'

**Expected behavior**
I wonder how to run this python code successfully and how to generate my own scenarios, thanks !

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CARLA Version 0.9.5
 - Python version 3.7
 - scenario_runner 0.9.5.1

**Comment by fabianoboril** [comment]
If you still experience this issue, please update to a newer release. We added several fixes to the route execution.
