### ISSUE TITLE
How do I get the exact location (x, y, z) on the map to spawn actors?

### ISSUE THREAD

**Issue by c1enet** [carla-simulator/scenario_runner#40]
Hello,
I'm new to Carla.
Got a question while I was just trying out the API by creating some sample scenarios. 
I was wondering if there is an easy way to find out  the location value of a point on the map.
Thanks for your time!

**Comment by fabianoboril** [comment]
Either you open the map in the Unreal editor and find the desired coordinates, or you drive with the manual client to the position you like, and note then note the coordinates.

**Comment by damascenodiego** [comment]
Recently, I've implemented a small [code to print the spectactor's current position on Carla 0.9.5.](https://gist.github.com/damascenodiego/c53ae6960f1ebdcc25d41384392b6500)

Remind that the scenario runner's release works for 0.9.2 and you will need to make some adjusts on it. More specifically, you'll need to **change line 14** to the right path where the .egg files are found.

**Comment by ornare** [comment]
@fabianoboril Is the z coordinate data stored in OpenDrive files maybe?

**Comment by youngsend** [comment]
I opened the OpenDRIVE file with `odrViewer`. `odrViewer` will show x, y, z coordinate of the cursor position. However the free `odrViewer` seems to have disappeared from Internet...

**Comment by henkenen** [comment]
> Either you open the map in the Unreal editor and find the desired coordinates, or you drive with the manual client to the position you like, and note then note the coordinates.

Could you give me some hints on how to get the coordinates in Unreal editor?
