### ISSUE TITLE
OpenScenario coordinates/heading are not working on newest commit in master branch.

### ISSUE THREAD

**Issue by jS5t3r** [carla-simulator/scenario_runner#418]
When I check out the newest commit `git co ffd8f8c1d51344bf8037233006725eda654df6a4`, 
the coordinate system of the spawning vehicles don't work anymore. The coordinates/heading do not correspond to the displayed ones when starting 'manual_control.py'.

**Comment by fabianoboril** [comment]
Hi,
with a recent commit we updated the handling of coordinate systems #396. Since then, you need to put a CARLA: as prefix to your scenario name, as otherwise the standard coordinate system of OpenSCENARIO (OpenDRIVE) is used (which is rotated by 180° to the CARLA one).
