### ISSUE TITLE
One Bug when I create a scenario multiple times in one route.

### ISSUE THREAD

**Issue by GilgameshD** [carla-simulator/scenario_runner#422]
**Describe the bug**
I use challenge mode and use Scenario_4 in Town05. My route samples three _VehicleTurningRight_ scenarios. However, after the first scenario ends, the other two are never triggered. I printed the scenario_tree and find out that the names of the root node of these scenarios are the same.

My solution is adding an index to each root node and it works well. It is a possible bug that has not been noticed when creating a scenario multiple times in one route.

**To Reproduce**
1. python3 scenario_runner.py --route ... ... --agent ...

**Expected behavior**
In one route, scenarios will not interact with each other.

**Screenshots**
This is a screenshot that shows the scenario_tree, in which I have three Scenario_4 with the same root name. This happens just after the first scenario ends. The expected behavior is that only one of these scenarios finished, but what I get is all three scenarios end.
![Screenshot from 2020-01-09 18-51-43](https://user-images.githubusercontent.com/13979878/72114891-0d5fd180-3313-11ea-93ca-5f2e77d920ae.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CARLA Version CARLA 0.9.6
 - Python version 3.7
 - Version 0.9.6

**Comment by fabianoboril** [comment]
Hi,
thank you very much for raising this issue. I uploaded a hotfix #423, which resolves this issue.
