### ISSUE TITLE
Support for 0.9.7

### ISSUE THREAD

**Issue by amstrudy** [carla-simulator/scenario_runner#435]
Hi all,

Is there any planned support for the newest CARLA release (0.9.7)? There is another issue (#430 ) describing a bug due to the new Traffic Manager. I just wanted to check before I get my hands dirty with the wrong CARLA install.

Thanks!

**Comment by fabianoboril** [comment]
Hi,
you can use the current master with 0.9.7. Yet there are still some issues. As long as you use OpenSCENARIO you should be good to go. Problems mostly occur w.r.t route-based scenarios.
