### ISSUE TITLE
OpenSCENARIO Catalog support

### ISSUE THREAD

**Issue by amstrudy** [carla-simulator/scenario_runner#459]
Has there been any work to support catalogs in OpenSCENARIO? They would be very useful when making a bunch of similar scenarios.

A use case would be when creating a new entity one could simply having a catalog reference rather than re-defining the same vehicle in multiple files.

I don't see any other requests for it, but I wanted to check before beginning to implement a solution.

**Comment by fabianoboril** [comment]
Hi,
we did not yet start working on this. If you have anything working we would be very happy if you could share it with us and the community.

**Comment by amstrudy** [comment]
@fabianoboril Just a quick question: what is the purpose of lines 258-260 of `open_scenario.py` shown here
```python
parallel_actions.add_child(
    oneshot_behavior(variable_name=get_xml_path(self.config.story, child),
                    behaviour=maneuver_behavior))
```
Due to the nature of catalogs, the `get_xml_path()` is proving to be difficult. What is that path used for?
