### ISSUE TITLE
Vehicles do not move

### ISSUE THREAD

**Issue by gregoryps1989** [carla-simulator/scenario_runner#46]
Vehicles are spawned but do not move. No obvious errors. Has anyone encountered the same?

**Comment by hayakawa3210** [comment]
me too.

**Comment by hayakawa3210** [comment]
Sorry, I used anther file.
I had to use.
> python ../scenario_runner/scenario_runner.py --scenario FollowLeadingVehicle
> python ../scenario_runner/manual_control.py

But I used.
> python  ../CARLA_0.9.3/manual_control.py

When I move to near  a leading car,  leading car start to move.
