### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'config_file'

### ISSUE THREAD

**Issue by ravishk1** [carla-simulator/scenario_runner#462]
Getting this error by running command :- python3 scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld

Traceback (most recent call last):
  File "scenario_runner.py", line 619, in <module>
    sys.exit(main())
  File "scenario_runner.py", line 609, in main
    result = scenario_runner.run()
  File "scenario_runner.py", line 529, in run
    result = self._run_scenarios()
  File "scenario_runner.py", line 423, in _run_scenarios
    self._args.config_file)
**AttributeError: 'Namespace' object has no attribute 'config_file'**

Carla Version :- 0.9.6 and 0.9.7 (same error)

Any suggestions , to solve this issue ?

**Comment by jackbart94** [comment]
Hi,

There's an error in main, where line 423 in scenario_runner.py is:
``` 
self._args.config_file
```

but should instead be:

```
self._args.configFile
```

Let me know if this fixes your issue!
