### ISSUE TITLE
Walker falling through earth

### ISSUE THREAD

**Issue by amstrudy** [carla-simulator/scenario_runner#472]
**Describe the bug**
Somehow the most recent commits (not sure which one but starting with 0812d3a) combined with the update to 0.9.7 is causing pedestrians to fall through the earth as soon as they are spawned.

**To Reproduce**
1. Run `python3 scenario_runner.py --openscenario srunner/examples/PedestrianCrossingfront.xosc`

**Expected behavior**
The pedestrian should spawn down the road from the ego vehicle and fall a little and hit the sidewalk, then stand. Instead, the pedestrian just continues falling through the sidewalk.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CARLA Version 0.9.7
 - Python version 3.6.9
 - Version 0.9.7

**Comment by fabianoboril** [comment]
Fix is available in PR #473
