### ISSUE TITLE
Argument Error with running route-based scenario

### ISSUE THREAD

**Issue by aroongta** [carla-simulator/scenario_runner#493]
**Argument Error with running route-based scenario**
The getting-started documentation for the scenario runner has an example to use the route-based scenario. The "route" argument seems not a valid argument for the scenario_runner.py script. 
`python scenario_runner.py --route <path/to/route-file> <path/to/scenario_sample_file> [route id]`

Therefore I receive an error saying the argument is unrecognized. 

**Expected behavior**
I expected it to launch the Carla AD challenge route. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42918572/77256358-1ee32500-6c44-11ea-82e0-56a3867f1caf.png)

I am trying to generate a route based test track to have users drive using a Logitech G920 controller and record cognitive signals. Please look into the problem and let me know the best way to debug it. 

**Desktop and Carla Specs:**
 - OS: Ubuntu 16.04
 - CARLA Version [CARLA 0.9.6]
 - Python version [ 3.5]
 - Version [ 0.9.6]

**Comment by fabianoboril** [comment]
Try to add --route in front of your arguments.

**Comment by aroongta** [comment]
Hi @fabianoboril ,
I did try to add --route, still get the same unrecognized argument error. 
Also, I cannot find the --route argument definition in the scenario_runner.py. I am not sure if it is supposed to be like that. 
Please look into it and let me know.

Thank you

**Comment by glopezdiest** [comment]
Hello @aroongta, what version of scenario_runner are you using? The --route argument has been there for a very long time now and you should most definitely have it.

**Comment by aroongta** [comment]
Hello @glopezdiest ,
I am using the 0.96. 
Figured it, the zipped files for some reason are lacking the argument definition. I cloned the repository, those seem to have all the definitions. Probably the zipped folders are not updated. 

Thank you.

**Comment by gurpreet2-kaur** [comment]
The example scenario file all_towns_traffic_scenarios.json given in Carla code doesnot work for route based scenario fails with error " Some scenarios are failing"
Any reference  to a simple scenario configuration file so that I can successfully run a route based scenario.
