### ISSUE TITLE
Not able to run scenario

### ISSUE THREAD

**Issue by AMRITKV88** [carla-simulator/scenario_runner#494]
@deepakreddy63 

When I am trying to run the follow vehicle scenario using the command :

`python3 scenario_runner.py --reloadWorld  --scenario FollowLeadingVehicle_1`

and manual_control.py on other terminal using the command : 

 `python3 manual_control.py --autopilot`

The pygame window pops-up and it runs, but still I am getting such **Failure** errors as mentioned below.

I am getting following errors in scenario terminal :

```
Preparing scenario: FollowLeadingVehicle_1
ScenarioManager: Running scenario FollowVehicle
Resetting ego-vehicle!
Destroying ego-vehicle!
Failure!
Destroying ego vehicle 434
No more scenarios .... Exiting
```

And in the manual_control.py terminal the error is:

```
Scenario ended -- Terminating
ERROR: failed to destroy actor 434 : unable to destroy actor: not found 
Fatal Python error: PyEval_SaveThread: NULL tstate
```
I am quite new to this CARLA, so I followed the getting_started tutorial. But not able to handle this error. Please help me out.

**Screenshots**
Here I am attaching one such failure run screenshot.
![Screenshot (242)](https://user-images.githubusercontent.com/52911458/77407280-e8d8a900-6ddb-11ea-93b9-51b2fd3ee074.png)

**Desktop:**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.8]
 - Python version [e.g. 3.6]
 - Version [e.g. 0.9.8]

**Thanks in advance....!**

**Comment by fabianoboril** [comment]
Hi,
the scenario was successfully executed, but some of the evaluation conditions (i.e. tests) failed. Please run with --output to get further info.

**Comment by AMRITKV88** [comment]
@fabianoboril Thanks for the update. I tried the same, but I am unable to understand completely. As per my understanding its showing that expected time is 60.00s but it took 60.05s. Am I right ? But again in system time its showing 17.22s.  Is there anything I am missing or something other which need to be changed. Please suggest the edits required.
I am attaching a screenshot here for your reference; after running the command with --output keyword. Please help.

![Screenshot (244)](https://user-images.githubusercontent.com/52911458/77644778-99cf7700-6f87-11ea-9638-1768145eb807.png)

**Comment by fabianoboril** [comment]
The CARLA time can be faster than system time depending on the performance of your system, rendering quality, amount of sensor etc. Please see the CARLA documentation for further information.

**Comment by villinux** [comment]
Hi 
I have the same problem.
Every scenario i try to run failes after 10 to 20 seconds. I have already tried --output but i get same result as mentioned above. How can this be fixed?

**Comment by fabianoboril** [comment]
Well, this depends on the exact failure. Did you connect an agent (e.g. by running manual_control.py) to the ego vehicle, and drove around? If this is the case, take a look at the exact condition that failed. All scenarios are designed to just run for a fixed amount of (CARLA) time, and afterwards terminate.

**Comment by villinux** [comment]
I tried manual_control but i can only drive while the scenario is running. When it fails the manual control terminates immediatly. 
I haven't used an agent yet

**Comment by zeinebghaddab** [comment]
Hi , i'm trying to simulate ego vehicles on carla using openscenario file, i don't want to control the vehicle using manual control, i want that  the vehicle  follow a specific path that i define. could anyone help me with openscenario example?

**Comment by TigerStone93** [comment]
> The CARLA time can be faster than system time depending on the performance of your system, rendering quality, amount of sensor etc. Please see the CARLA documentation for further information.

What does it exactly mean?

**Comment by spartan-tridoan** [comment]
Hi, if we cannot run with manual_control.py or having to wait for ego vehicle. We can try to human_agent what simulating what we will interact with the car
```
python scenario_runner.py --openscenario scenarios/template.xosc --agent srunner/autoagents/human_agent.py
```
