### ISSUE TITLE
Actor vehicles losing control in left turn scenario 

### ISSUE THREAD

**Issue by JeffTheHacker** [carla-simulator/scenario_runner#502]
Question description: 
In the scenario Signalized-Left-Turn, the actor vehicles are being spawned in a stream as I control the ego vehicle trying to make an unprotected left turn. However, the actor vehicles seem to lose control after several seconds. 

Expected behavior: 
The actor vehicles are supposed to move in a straight line across the intersection. However, when I run the scenario, the actor vehicles move straight for about two seconds, and then they lose control. One actor vehicle deviates from its straight path and comes crashing at my ego vehicle. The other actor starts swirling in circles. 

Screenshot: depicts the moment when the actor vehicle hits me 
<img width="750" alt="屏幕快照 2020-04-01 下午8 20 24" src="https://user-images.githubusercontent.com/42763168/78207335-3d23fe80-7456-11ea-830c-39031f94a7be.png">

Desktop
 - OS: Ubuntu 18.04
 - CARLA Version: 0.9.8
 - Python version: 3.5
 - Version: 0.9.8

**Comment by fabianoboril** [comment]
Hi,
I can reproduce the problem. Let's see, if this can be fixed.

**Comment by fabianoboril** [comment]
I created a fix for this issue. Please see PR #504
