### ISSUE TITLE
can carla-challenge-1.0 still support carla-0.9.9 ?

### ISSUE THREAD

**Issue by whuxhzhang** [carla-simulator/scenario_runner#557]
Hi

I have upgraded to carla-0.9.9,  and I want to test my code with carla-challenge, can carla-challenge-1.0 still support carla-0.9.9 ?

**Comment by fabianoboril** [comment]
You can still use agents and routes, so yes you can still run the challenge scenarios. However, the execution changed a bit, so did the output. Please have a look into the updated documentation.

**Comment by whuxhzhang** [comment]
thank you very much,  I will try to debug them.
