### ISSUE TITLE
How to use the scenarios of scenario_runner to reninforcement learning directly？can you give a examble for us？

### ISSUE THREAD

**Issue by zengsh-cqupt** [carla-simulator/scenario_runner#565]
**Describe our question or idea**
A clear and concise description.
How to use the scenarios of scenario_runner to reninforcement learning directly like OpenAI gym envs？can you give a examble for us？ Can the scenario_runner work well on Ubuntu18.04?
So far，I find I can‘t use the the scenarios of scenario_runner to reinforcement learning like OpenAI gym envs. If I code my scenarios by myself, it will take me very much time. I wanna save time, and focus on the agent of reninforcement learning.

**Expected behavior**
I can train my reinforcement learning agent using the scenarios of scenario_runner directly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.9]
 - Python version [e.g. 3.5]
 - Version [e.g. 0.9.9]

**Comment by jingzhengli** [comment]
I have the same question...
