### ISSUE TITLE
Scenario not yet ready with manual_control.py

### ISSUE THREAD

**Issue by sissiok** [carla-simulator/scenario_runner#567]
I tried to run manual_control.py, but only a black window popped out and in the terminal I got message "scenario not yet ready". What went wrong? Is there anyone can help me with it?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CARLA Version: CARLA 0.9.9
 - Python version: 3.6
 - Version: 0.9.9

**Comment by glopezdiest** [comment]
Nothing went wrong. The manual control at ScenarioRunner doesn't create any vehicles. It instead attaches to an already spawned vehicle which has the "hero" rolename (the ego vehicle). If that isn't the case, the *Scenario not yet ready* will constantly pop up until the vehicle is created

**Comment by fabianoboril** [comment]
Copy of #566. Let's close this one, and continue in #566.

**Comment by sissiok** [comment]
Thank you. It is solved.
