### ISSUE TITLE
What tool do you use to create scenarios in the openscenario format?

### ISSUE THREAD

**Issue by AIasd** [carla-simulator/scenario_runner#576]
Hi! I wonder what tool do you use to create the openscenario examples (*.xosc files) in the folder srunner/example?I want to create some scenarios on my own in this format and hope you can recommend a tool to use for this purpose. Thanks!

**Comment by fabianoboril** [comment]
Currently you can use any XML editor. There is not GUI, if you are looking for that.

**Comment by AIasd** [comment]
I see. Thanks for letting me know!
