### ISSUE TITLE
Running scenario results in crashing UE4

### ISSUE THREAD

**Issue by wajo07** [carla-simulator/scenario_runner#595]
**Problem:**
I have a problem running a route.. everytime I run the command unreal crashes. Below I attached the Output and Unreal Log file.

I also tried running a simple DynamicObjectCrossing scenario in Town2 with the following command: 
python scenario_runner.py --scenario DynamicObjectCrossing_1 --reloadWorld

but it crashed as well with the same output.. hope anybody can help.

**Output of running route:**
![grafik](https://user-images.githubusercontent.com/38495478/87330357-c3151280-c538-11ea-880d-44d03b77314e.png)
[CarlaUE4.log](https://github.com/carla-simulator/scenario_runner/files/4913907/CarlaUE4.log)

**Desktop (please complete the following information):**
 - OS: Windows10
 - CARLA Version 0.9.9
 - Python version 3.8.1
 - Version 0.9.9

**Comment by glopezdiest** [comment]
As we discussed at the CARLA discord server, CARLA 0.9.9 has a problem when reloading the world. Using 0.9.9.3 and above fixes this issue.
