### ISSUE TITLE
ScenarioRunner AttributeError: module 'signal' has no attribute 'SIGHUP'

### ISSUE THREAD

**Issue by hnuma** [carla-simulator/scenario_runner#601]
Hello,

I want to ask an error I take on installation steps of ScenarioRunner. When I run "python scenario_runner.py --scenario OppositeVehicleRunningRedLight011" command, I encounter AttributeError: module 'signal' has no attribute 'SIGHUP'.

How can I remove this error, could you help?

![sighup error](https://user-images.githubusercontent.com/46264101/88234813-485b9e00-cc82-11ea-9edd-70a5a9b9f1d3.png)

 - OS: [Windows 10]
 - CARLA 0.9.9.4
 - Python 3.7
 - [scenario_runner-0.9.9]

**Comment by DevotionGit** [comment]
Windows  not support  this.comment this line,it run well.

**Comment by hnuma** [comment]
@DevotionGit thank you for your reply. I did it, it worked.
