### ISSUE TITLE
Error using get_light_state

### ISSUE THREAD

**Issue by s-rajab** [carla-simulator/scenario_runner#602]
Hello,

I am trying to get the light status of all vehicles in the world:

`import carla
from srunner.scenariomanager.carla_data_provider import CarlaDataProvider, CarlaActorPool
world = CarlaDataProvider.get_world()
actor_list = world.get_actors()
for target_vehicle in self.actor_list.filter('vehicle.*'):
      lights = target_vehicle.get_light_state()`

However, I am getting the following error:

AttributeError: 'Vehicle' object has no attribute 'get_light_state'
'Vehicle' object has no attribute 'get_light_state'

![image](https://user-images.githubusercontent.com/67026071/88340236-7c2dd680-cd09-11ea-86e8-4afe219200b5.png)

I appreciate any help.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - CARLA Version 0.9.7
 - Python version 3.5
 - Version 0.9.7

**Comment by glopezdiest** [comment]
Hey @s-rajab. Vehicle lights were introduced in CARLA 0.9.8, so you are just one version short.

**Comment by s-rajab** [comment]
Thanks @glopezdiest. I guess it's time to upgrade then.
