### ISSUE TITLE
Have Problems to create my own scenario

### ISSUE THREAD

**Issue by Leon-Adler** [carla-simulator/scenario_runner#617]
Hi all,

I followed the instructions (https://github.com/carla-simulator/scenario_runner/blob/master/Docs/creating_new_scenario.md) to create my own scenario. So I created a empty Python Class and filled it with existing Code (e.g. from FollowLeadingVehicle) and added a new Scenario Configuration as a XML file.

However, after running the scenario "NewScenario" with the scenario_runner.py I got the execption: 
"Configuration for scenario NewScenario cannot be found!" (Line 384 in the scenario_runner.py)

So I looked in the responsible function find_scenario_config() in scenario_parser.py and have the assumption that the scenario name is not returned correctly. 

    - Has anyone already had similar problems creating their own scenario and could help me?
    - Do I just have to create a class and a corresponding XML for it or do I have to import my class somewhere?

Thanks a lot!

**find_scenario_config():**
![parser](https://user-images.githubusercontent.com/65609568/90757950-8e863a80-e2de-11ea-8c96-49adcb3d4907.png)

**XML file:**
![xml](https://user-images.githubusercontent.com/65609568/90757954-8f1ed100-e2de-11ea-8fa5-1c66b0fd3b5a.png)

**Comment by glopezdiest** [comment]
Hey @Leon-Adler. Before anything, the Docs are quite old and while the process remains the same, there might be some minor changes.

Having said that, where are you saving your XML file? By default, ScenarioRunner looks for the xml at *srunner/examples*. If it is not there, it won't be found. If you don't want to put your file there, you can use the *--configFile* argument to tell SR where is your XML file located. There is no need to import anything.

Additionally, this is the same for the *.py* file, which is looked at *srunner/scenarios*. *--additionalScenario* is the argument in case another path is needed.
