### ISSUE TITLE
Have problems when using my own xosc&xodr files

### ISSUE THREAD

**Issue by H-Whisky** [carla-simulator/scenario_runner#618]
**Describe our question or idea**
Hi, First I was using the following python script that it can load the static scene in UE4_Carla :
`python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld`
On my understanding, the script may be running FollowLeadingVehicle.xml & follow_leading_vehicle.py, and it works well!

Then when I want to use the following script to run FollowLeadingVehicle.xosc to load the scene, and it can works but the obstacle vehicle can nit move.
`python scenario_runner.py --openscenario ./srunner/examples/FollowLeadingVehicle.xosc --reloadWorld`

Finally, I want to use the following script to run my own xosc file to import my own map and  load the scene but it fails:
`python scenario_runner.py --openscenario ./srunner/examples/CF_1_LO_2_CO_1_carla.xosc --reloadWorld`

**Expected behavior**
I hope to be able to load the scene into UE4 when I execute the script：
`python scenario_runner.py --openscenario ./srunner/examples/FollowLeadingVehicle.xosc --reloadWorld`
and the ego_car and obs_vehicle can both move when I run manual_control.py.
If possible, I wish that I could use the script to run my own customized .xosc & .xodr file, Thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/38555602/91034569-cae7cc80-e637-11ea-9ce7-49afa4a87945.png)
I can import my own map(.xodr) into UE4_carla, but It seems that it cannot be read when parsing to town.

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 - CARLA Version: CARLA 0.9.9
 - Python version: 3.6.9
 - Version: maser

**Comment by SExpert12** [comment]
When I run this:
python3 scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld
I am getting the error:
 warnings.warn(msg, UserWarning)
Configuration for scenario FollowLeadingVehicle_1 cannot be found!
No more scenarios .... Exiting

Can you help me to resolve?
