### ISSUE TITLE
Branch for v0.9.9

### ISSUE THREAD

**Issue by stonier** [carla-simulator/scenario_runner#630]
**Describe the bug**

`README.md` indicates there is a `0.9.9` branch, but there is not. The `0.9.9` tag is pretty old (April and 62 commits behind) - not sure whether master is incorporating patches for `0.9.9` or if there hasn't been any patching of the original tag. A branch would resolve that conundrum and be a constant url for fetching purposes.

**Expected Behaviour**

A `0.9.9` branch exists.

**Comment by fabianoboril** [comment]
Fixed with #647 and #648
