### ISSUE TITLE
Support on Important OSC tags

### ISSUE THREAD

**Issue by sagar-g-v** [carla-simulator/scenario_runner#638]
Hi, 
We are using scenario runner with OpenScenario 1.0 in our project.

we have created many scenarios using the currently supported tags.  
but going further we need to use some more tags available in OpenScenario 1.0 for our scenarios.

## Add support for the Following

- [x] `RelativeTargetSpeed`:
    - supported but the following behaviour is observed.
    when this tag is used we are getting this error.  
   `Local variable 'target_speed' might be referenced before assignment`

    - `openscenario_parser.py`
    ```python
    atomic = ChangeActorTargetSpeed(actor,
                                        target_speed,
                                        relative_actor=obj_actor,
                                        value=value,
                                        value_type=value_type,
                                        continuous=continuous,
                                        distance=distance,
                                        duration=duration,
                                        name=maneuver_name)
    ```
    here `target_speed` is not defined/initialized.
    so making `target_speed=0.0` will fix this issue.

- [ ] `LaneOffsetAction`:

    - needed for our scenarios

- [x] `TimeToCollisionCondition`:
    - supported but the following behaviour is observed.  
    - tag is working for position. but not working for reference Actor.  
    `TimeHeadwayCondition` is working for reference Actor.  

    - In the current implementation the `gap/headway/tailway` is calculated from center to center. so there is no distinction between `gap`, `headway` and`tailway`.

    ![alt text](https://www.researchgate.net/profile/Jiri_Ambros2/publication/309476899/figure/fig1/AS:547959508922368@1507655135464/Definition-of-gap-headway-and-tailway.png "TimeToCollisionCondition")

- [x] `AssignRouteAction`:  
    - supported but the following behaviour is observed.   
       I am using 4 events to control `TV01` Maneuver
        ```xml
        <Event name="TV01SetSpeed" priority="overwrite">...</Event>
        <Event name="TV01Route" priority="overwrite">...</Event>
        <Event name="TV01Route1" priority="overwrite">...</Event>
        <Event name="TV01EndState" priority="overwrite">...</Event>
        ```
        - `TV01SetSpeed`: `TV01` speed is set to 30 kmph.
        - `TV01Route`: waypoints to be followed are given.
        - `TV01Route1`: second set of waypoints to be followed are given.
        - `TV01EndState`: `TV01` speed is set to 0 kmph.  

    above events are executed sequencially by setting start condition as `endTransition` of previous Event.  

    __Expected Result__
        - above 4 events should run one after another in sequence
        - `TV01` should perform above Actions and come to `TV01EndState`  
    
    __Actual Result__
        - `TV01SetSpeed` and `TV01Route` are completed sucessfully.
        - after `TV01Route` `TV01` is stoping at last waypoint.
        - `TV01Route1` and `TV01EndState` not working.

    __My observation after debugging__
    - In `npc_vehicle_control.py` waypoints are updated when `TV01Route` is triggered.
        
        - `npc_vehicle_control.py`
        ```python
        control = self._local_planner.run_step(debug=False)

        # Check if the actor reached the end of the plan
        if self._local_planner.done():
            self._reached_goal = True
        ```
    - At the end of the Route, `local_planner.run_step()` is returning control with `brake=1.0` irrespective of updated `target_speed` or `waypoints` from the next events `TV01Route1` and `TV01EndState`.
        - `local_planner.py`
        ```python
        if len(self._waypoints_queue) == 0 and len(self._waypoint_buffer) == 0:
            control = carla.VehicleControl()
            control.steer = 0.0
            control.throttle = 0.0
            control.brake = 1.0
            control.hand_brake = False
            control.manual_gear_shift = False

            return control
        ```

If the above things are taken care by next release it will be very helpful for us.  
__Can we get an estimated date of next stable release ?__

Thank you.

**Desktop:**
 - OS: Ubuntu 18.04
 - CARLA Version: CARLA 0.9.9.4
 - Python version 2.7
 - Version 0.9.9

**Comment by fabianoboril** [comment]
Hi,
are you using the ScenarioRunner 0.9.9 version? Do you mind testing the current master? The TimeToCollision condition is supported, and I think some of your reported observations are fixed as well.
