### ISSUE TITLE
A possible bug of RunningRedLightTest::rotate_point()

### ISSUE THREAD

**Issue by emailweixu** [carla-simulator/scenario_runner#643]
**Describe the bug**

It seems there is a bug of rotate_point() function for  RunningRedLightTest

https://github.com/carla-simulator/scenario_runner/blob/e4241813f39554be048c274c8e5e05f778d85f6a/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L1829-L1835

If the angle is 0, the returned vector becomes Vector3D(point.x, -point.y, point.z), which is different from the original vector. And the function doesn't even perform a rotation. Because the transformation matrix it uses is [[cos, -sin], [sin, -cos]], which is not a rotation.

**Comment by fabianoboril** [comment]
@glopezdiest Can you have a look into this?

**Comment by glopezdiest** [comment]
Sure, I'll take a look and report back

**Comment by glopezdiest** [comment]
Hey @emailweixu, many thanks for seeing that. Indeed, that rotation "matrix" was wrong, and vectors with y components weren't being rotated properly. This has been fixed at a PR. However, this wasn't affecting the current criteria, as all rotated vectors only had *x* component.
