### ISSUE TITLE
scenario runner output file

### ISSUE THREAD

**Issue by soheilade** [carla-simulator/scenario_runner#645]
in scenario runner the --file switch is supposed to direct the output into a file
`parser.add_argument('--file', action="store_true", help='Write results into a txt file')`
could somebody please say where is this file located? I cannot see any new file in the working directory after running scenario_runner.py with --file, try passing an argument to --file, for example --file a.txt, leads to an error ...

**Comment by fabianoboril** [comment]
Hi,
which version of SR are you using?

**Comment by soheilade** [comment]
Hi Fabian, 0.9.9

**Comment by soheilade** [comment]
the generated file is a hidden file, so you must run` ls -la` to be able to see it!
