### ISSUE TITLE
Autopilot does not work in 0.9.10

### ISSUE THREAD

**Issue by kino3** [carla-simulator/scenario_runner#657]
**Describe the bug**
autopilot mode in manual_control.py does not work (ego vehicle does not start automatically) in the newest carla 0.9.10.1 and scenario runner plugin (both 0.9.10 and master as of 2020-10-09)

**To Reproduce**
1. build and launch Carla server (0.9.10.1) 
2. `python scenario_runner.py` (specify the python scenario or openscenario)
3. `python manual_control.py -a`
4. Ego vehicle does not start (though I push `P` button repeatedly)

"`spawn_npc.py`" and "`manual_control.py -a`" in Carla original (`/PythonAPI/examples`) can work well, so It may be a Scenario Runner problem, I assume.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - CARLA Version [CARLA 0.9.10.1]
 - Python version [3.6]
 - Version [0.9.10]

**Comment by glopezdiest** [comment]
Hey @kino3. Indeed you are right. We added synchronous TM to SR at 0.9.10 but it was always being set to synchronous, even at async simulations, which was causing problems. This PR should fix it
