### ISSUE TITLE
question about stable version

### ISSUE THREAD

**Issue by sagar-g-v** [carla-simulator/scenario_runner#663]
Hi,

I have been using scenario runner 0.9.9 till now.

now i want to start using 0.9.10 and its new features.

But 0.9.10 is still not stable to satart using it completely.

can i know how long will it take to make current version as stable?

if any help needed to evaluate the functionalties. I can help.

Regards,
Sagar G V

**Comment by fabianoboril** [comment]
Hi,
do you refer to that there is no 0.9.10 branch? You could use the tag v0.9.10, or simply stick to master. API breaking changes should not happen to many now, since we mostly work on bringing in new OSC features, which should happen under the hood.

**Comment by sagar-g-v** [comment]
I think sticking to `master` makes sense.
I will evaluate master branch and find issue and fixes.

Thank you.
