### ISSUE TITLE
Incorrect function calls

### ISSUE THREAD

**Issue by kael53** [carla-simulator/scenario_runner#680]
**Describe the bug**

There are several places where set_velocity and set_angular_velocity of the Vehicle class are incorrectly-accessed by scenariomanager as set_target_velocity and set_target_angular_velocity.

**To Reproduce**
1- Run the carla-simulator
2- Run the FollowLeadingVehicle scenario using scenario-runner
3- Run manual_control.py
4- Press throttle, and see the error produced by scenario-runner

**Expected behavior**

I would expect it to successfully run, but it crashes after the error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CARLA Version CARLA 0.9.10
 - Python version 3.6
 - Version 0.9.10

**Additional context**

**Comment by fabianoboril** [comment]
The problem is that you use ScenarioRunner master with an pre-0.9.10 CARLA version. Please either update CARLA to 0.9.10 or use the 0.9.9-branch of ScenarioRunner.
