### ISSUE TITLE
Creating new scenario .

### ISSUE THREAD

**Issue by akshatamk** [carla-simulator/scenario_runner#684]
Hello,
   how to create new scenarios in carla. Is it only only by creating python file(scripting) and the related XML file? Is there any scenario editor available for carla?
Please help!

**Comment by seowwj** [comment]
Related to #661

**Comment by glopezdiest** [comment]
Currently, there is no editor available for the creation of scenarios. As you pointed out you have to either use the python file, or use the OpenScenario format.

**Comment by akshatamk** [comment]
@glopezdiest Thank you for the response

**Comment by GeneralMak** [comment]
I have the similar problem,the official said to create a new scenario (https://carla-scenariorunner.readthedocs.io/en/latest/creating_new_scenario.html),four methods need to be defined .But how to define the parameters of this  _initialize_actors method  and create_behavior method, I have'nt found a good turorial.  Ask for help!!!

**Comment by GeneralMak** [comment]
I imitated the official examples to define the parameter values in my own method,but various errors will be reported during runtime,so I would like to ask for if any scholars have made them.

**Comment by GeneralMak** [comment]
@fabianoboril  hello, Can you guys give a detailed tutorial on how to create Initialize Method and CreateBehavior method?(https://carla-scenariorunner.readthedocs.io/en/latest/creating_new_scenario.html)

**Comment by fabianoboril** [comment]
Why not using OpenSCENARIO? This is much easier, and there is a graphical scenario editor: https://github.com/carla-simulator/traffic-generation-editor?

**Comment by GeneralMak** [comment]
@fabianoboril  ok, Thank you for the response! I'will try.

**Comment by GeneralMak** [comment]
@fabianoboril  ok, Thank you for the response! I'will try.
