### ISSUE TITLE
cannot load scenario

### ISSUE THREAD

**Issue by shimizhang** [carla-simulator/scenario_runner#686]
**I run into the following same error of each scenario**
When I run python scenario_runner  while open the manual_control, for each scenario I run into the "ERROR: failed to destroy actor 206: unable to destroy actor: not found" issue.

Who can tell me what is happening and how to fix this?

**Screenshots**
![image](https://user-images.githubusercontent.com/56880104/99489738-64bcce00-2936-11eb-8b2c-2bcf3b0b4fa4.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - CARLA Version [e.g. CARLA 0.9.10]
 - Python version [e.g. 3.7]
 - Version [e.g. 0.9.10]

**Comment by glopezdiest** [comment]
Hey @shimizhang , that isn't really an error but a warning. It is caused by trying to destroy an actor that is already dead, but it doesn't affect the simulation. In other words, ignore it.
