### ISSUE TITLE
Debugging python code inside Carla in VS Code?

### ISSUE THREAD

**Issue by kino3** [carla-simulator/scenario_runner#690]
I'm using VSCode (in Ubuntu) to debug python code in this plugin. In some cases, I would like to debug the carla's python code (not in scenario runner's) by setting breakpoints etc. I'm trying but cannot find best way yet.
It would be helpful that someone to provide the example configuration of launch.json, settings.json etc..

**Comment by kino3** [comment]
Sorry, I answer my own question by [using settings.json and .env](https://binx.io/blog/2020/03/05/setting-python-source-folders-vscode/) properly.

**Comment by slabban** [comment]
Hi Kino, any chance you can share your exact changes to the json file, I suspect I'm missing some important step.
