### ISSUE TITLE
OpenScenario 1.0.0 

### ISSUE THREAD

**Issue by Vela-zz** [carla-simulator/scenario_runner#695]
Recently, I used esmini/pyoscx  to generate openScenario 1.0.0 standard file, then using carla/scenario_runner collaboration for 
simulating, and I found some Condition tag, such like **TakeHeadAwayCondition**.. and some attribute in tag, like /**freespace**/ in **RelativeDistanceCondition**.

can scenario_runner team add a list about  tags or attributes of openScenario which can be used in carla scenario_runner?

**Comment by glopezdiest** [comment]
Hey @Vela-zz, you can check the current support of OSC [here](https://carla-scenariorunner.readthedocs.io/en/latest/openscenario_support/)

**Comment by Vela-zz** [comment]
> Hey @Vela-zz, you can check the current support of OSC [here](https://carla-scenariorunner.readthedocs.io/en/latest/openscenario_support/)

Thank you !
