### ISSUE TITLE
Description for the criteria faliure

### ISSUE THREAD

**Issue by tecena** [carla-simulator/scenario_runner#708]
Hello,

    When ever we run a test criteria, the result we are getting is either SUCCESS - TRUE or FALSE.
![image](https://user-images.githubusercontent.com/75019091/102192254-8c289b80-3ee0-11eb-8a07-96ebe3834bbe.png)
we are not getting any reason for the failure. Is there any way to get the description about failure as why is this criteria failed. what is the reason for the failure. 
And for Duration criteria we always get as failure ,since the ego vehicle does not stop within the specified time. How to correct it. 
Please help!

**Comment by fabianoboril** [comment]
Hi,
I think you have already everything at hand, that you are looking for. The expected value represents that target value of the criterion, and the actual value is the one that you vehicle under test achieved in the scenario. Take for example the KeepLane criterion. It is expected that this is never violated (expected value = 0). However, your vehicle left the lane 4 times (actual value = 4). Hence, success is false, i.e. failure.
