### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by togaen** [carla-simulator/scenario_runner#725]
**Describe the bug**
In the 'challenge evaluation' section of the README, the tutorial link is broken. The document it links to was removed in 31e4c80c0496c243a33649dc2aab743720de0b03.

**To Reproduce**
1. Go to README.md
2. Click on 'this tutorial' in the Challenge Evaluation section

**Expected behavior**
Link should go to a document.

**Screenshots**
n/a

**Additional context**
I would make a pull request to fix the link, but I don't know what an appropriate replacement for that link would be.

**Comment by glopezdiest** [comment]
Hey @togaen. Thanks for spotting that. That link was basically pointing to the CARLA Challenge 2019, which had a lot of very outdated information about scenario runner, so it was removed. That functionality is currently part of the [Leaderboard](https://github.com/carla-simulator/leaderboard, so maybe we could make that link point to it? I'm not sure right now, we'll think about it and report back.
