### ISSUE TITLE
Ego vehicle not found in manual_control

### ISSUE THREAD

**Issue by DeepAnonymous** [carla-simulator/scenario_runner#731]
Hi all,

I am new to scenario_runner, and I just want to run manual_control.py

However, the program just keep looping around "Waiting for the ego vehicle..."

`possible_vehicles = self.world.get_actors().filter('vehicle.*')
`
I tried to print `len(possible_vehicles)` and it shows **0**.

That means it cannot find any vehicle with the name `hero`.

Please help.

Thank you very much.

**Comment by glopezdiest** [comment]
Hey @DeepAnonymous, you have to first run a scenario with `python scenario_runner.py --scenario <scenario_name>` and then run that manual control on another terminal, to connect to the scenario you just started. Take into account that scenarios tend to have a 60s timeout, and after that, they'll be automatically stopped.

**Comment by DeepAnonymous** [comment]
Thank you for your reply.
