### ISSUE TITLE
Typo in getting started

### ISSUE THREAD

**Issue by sterres** [carla-simulator/scenario_runner#734]
The environment variable section for Windows in getting started has a typo

In the last line, there is a ":" instead of ";"

This causes the "import error: module 'agents' not found" error

>  %CARLA_ROOT% is the CARLA installation directory
> %SCENARIO_RUNNER% is the ScenarioRunner installation directory
> <VERSION> is the correct string for the Python version being used
> In a build from source, the .egg files may be in: ${CARLA_ROOT}/PythonAPI/dist/ instead of ${CARLA_ROOT}/PythonAPI
> set CARLA_ROOT=\path\to\your\carla\installation
> set SCENARIO_RUNNER_ROOT=\path\to\your\scenario\runner\installation
> set PYTHONPATH=%PYTHONPATH%;%CARLA_ROOT%\PythonAPI\carla\dist\carla-<VERSION>.egg
> set PYTHONPATH=%PYTHONPATH%;%CARLA_ROOT%\PythonAPI\carla\agents
> set PYTHONPATH=%PYTHONPATH%;%CARLA_ROOT%\PythonAPI\carla
> set PYTHONPATH=%PYTHONPATH%  **--> : <--**  %CARLA_ROOT%\PythonAPI

**Comment by glopezdiest** [comment]
Hey @sterres, that is indeed the case, thanks for pointing it out.
