### ISSUE TITLE
Invalid syntax when testing the example

### ISSUE THREAD

**Issue by dimmo90** [carla-simulator/scenario_runner#757]
I'm trying to run the test of scenario runner as per the documentation, however I am getting this error:
![image](https://user-images.githubusercontent.com/69709817/115837026-7f522080-a45b-11eb-9025-cc542690cfaf.png)

I am using python 2 to run it as I am trying to link scenario runner with CARLA and rosbridge, but it seems that simple_watchdog_timer.py is written in python 3?

Any help or a work around to achieve this link would be appreciated.

 - Ubuntu 18.04.5
 - CARLA 0.9.11
 - Python 2.7.17
 - Scenario runner 0.9.11 [package release]
 - ROS kinetic

**Comment by dimmo90** [comment]
All sorted now. Unfortunately I couldn't find a version that was compatible, however i found a workaround by replacing watchdog.py with a version from an earlier release (one that didn't reference simple_watch_timer).

**Comment by thiagodeborba** [comment]
hey @dimmo90 , i am getting the same issue how did/can you replace the watchdog.py file, what was the workaround, can you elaborate more, please?

**Comment by ParthAD3** [comment]
hey @dimmo90  i am facing the same issue, so how did you changed the file watchdog.py, what was the workaround, can you please elaborate more?

**Comment by dimmo90** [comment]
Hi @ParthAD3,

What version of scenario runner are you running? 0.9.10? because that should have the correct file and I wouldn't expect this problem to occur. It happened to me because I was trying to run scenario runner 0.9.11 with carla 0.9.11.

1) go into scenario_runner/srunner/scenariomanager/watchdog.py. Check line 14. If it says "import simple_watchdog_timer as swt" instead of "from threading import Timer" then I think you might have the 0.9.11 version. Because they advise you to have the same version of scenario runner as you do carla, I suggest you download scenario_runner 0.9.10 and the problem should go away (hopefully)
2) if it turns out you do have scenario_runner 0.9.10, then please post the error here and I'll try to help you out.

Cheers

**Comment by ParthAD3** [comment]
Hey, yes i was in tag 0.9.11 
but then i am gettig this problem 
![Screenshot from 2021-05-02 19-42-54](https://user-images.githubusercontent.com/71602780/116822415-f33ca900-ab7e-11eb-915e-a286d602f641.png)

**Comment by ParthAD3** [comment]
hey @dimmo90 yes i was on tag 0.9.11,  i have changed to 0.9.10 but now i am thrown with this issue " Configuration for scenario FollowLeadingVehicle_1 cannot be found 
i have updated the python, carla, and scenario runner paths,
simulation is playing 
all files are there, can you tell me the issue now ?
![Screenshot from 2021-05-02 19-42-54](https://user-images.githubusercontent.com/71602780/116822895-b6be7c80-ab81-11eb-9b25-29b864fa4644.png)

**Comment by ParthAD3** [comment]
hey @dimmo90 yes i was on tag 0.9.11, i have changed to 0.9.10, sry to bother on silly mistake
