### ISSUE TITLE
Question: How to create a route file to run a scenario for a specific route?

### ISSUE THREAD

**Issue by ParthAD3** [carla-simulator/scenario_runner#758]
**Describe our question or idea**
I want to create a route to test a scenario using: python scenario_runner.py --route <route_file_path> <scenarios_file_path> <route_name> --agent <agent_file>, but i have not much idea how to generate that route is it through rosbag?

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.10]
 - Python version [e.g. 2.7]
 - Version [e.g. 0.9.10]

**Comment by glopezdiest** [comment]
Hey @ParthAD3, routes are generally created manually, so they require some work. As you pointed out, they need a route file (example [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/data/routes_training.xml)), scenario file (example [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/data/all_towns_traffic_scenarios.json)) and your agent.

For routes, you need an xml with at least one route. Each route needs *id* (to differentiate between them), *town* (name of the map where they'll be run) and a list of *waypoint*. These serve as reference and SR will search for the shortest path between them, creating waypoints every meter (by default). Done [here](https://github.com/carla-simulator/scenario_runner/blob/9b244deab720e6e2e150f1f5b300cfecf352ba0b/srunner/scenarios/route_scenario.py#L186). Optionally, you can use *weather* to set a specific weather (you can just set one of the weather parameters, all of them, or any in between).

For the scenario file, you can set as many scenarios as you want, and SR will filter those your route passes through. This is probably the most useful and confusing feature routes have. The correspondence between the scenario names at the scenario file and their python class is done [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenarios/route_scenario.py#L53). This is probably the second most confusing feature.

Hope this helps, and yeah, everyone gets confused by routes at first.
