### ISSUE TITLE
No compatible version for carla .0.9.10? 

### ISSUE THREAD

**Issue by Brandeyy** [carla-simulator/scenario_runner#764]
After reading the documentary for the scenario runner I realised that there is no compatible version of the scenario runner for Carla Version 0.9.10. Is that true? 

Im new to Carla so its possible that I missed somethin

**Comment by glopezdiest** [comment]
Hey @Brandeyy, SR 0.9.10 is indeed compatible with 0.9.10

**Comment by Brandeyy** [comment]
That was probably a mistake on my side then. It says version 0.9.9 in scenario_runner.py script of sr 0.9.10 if i remeber correctly though.

**Comment by glopezdiest** [comment]
Ah, yeah, we might have forgotten to change that, but that's outdated. It still works fine

**Comment by Brandeyy** [comment]
Yea I was able to get it to work thanks for the quick responses
