### ISSUE TITLE
Relative Lane Change directions are mixed up for OpenSCENARIO/OpenDRIVE

### ISSUE THREAD

**Issue by sterres** [carla-simulator/scenario_runner#767]
Hi,

I had issues running lane changes in OSC 1.0 Scenarios with OpenDRIVE maps. It turned out, the direction is interpreted differently compared to other tools like esmini.

In OpenDrive, the Lanes are defined in this way:
| 2 | 1 | -1 | -2 |

https://releases.asam.net/OpenDRIVE/1.6.0/ASAM_OpenDRIVE_BS_V1-6-0.html#_lanes

But in OpenSCENARIO parser, a negative relative lane target is interpreted as "left". But it should be "right" (as you can see in the above ODR definition).

https://github.com/carla-simulator/scenario_runner/blob/ad71a2c7ed012d735be2b1158fca51b0761ff26b/srunner/tools/openscenario_parser.py#L1032

I don't know, if a change here would bring implications for use-cases that do not load ODR maps.

Best regards
Simon

**Comment by fabianoboril** [comment]
Well spotted. We should fix that.
