### ISSUE TITLE
[0.9.4] save_to_disk sometimes produces corrupted images

### ISSUE THREAD

**Issue by micmarty** [carla-simulator/scenario_runner#78]
I've encountered some weird behavior of `save_to_disk` method (from `carla.Image` class)
It seems like a half of all captured images are corrupted.

### My modification
The only thing I did was adding this line (`srunner/challenge/envs/sensor_interface.py`)
![image](https://user-images.githubusercontent.com/12485656/54074354-c4259800-4291-11e9-82eb-8519873570f9.png)

### Logs
Nautilus image browser:
> Could not load image '00192743.png'.
Fatal error reading PNG image file: IDAT: CRC error

![image](https://user-images.githubusercontent.com/12485656/54074237-60e73600-4290-11e9-817c-5ea3e635a272.png)

![image](https://user-images.githubusercontent.com/12485656/54074155-760f9500-428f-11e9-9e6e-3e4b16188b03.png)

### Solution ideas
Is anybody with same issues? Maybe `save_to_disk` is called to often?
What about adding `reading_frequency` to `sensor.camera.rgb` or threaded callback?

**Comment by fabianoboril** [comment]
Hi,
Maybe check this issue in the CARLA main repo. This seems to be not directly related to the scenario_runner.
