### ISSUE TITLE
How do you understand the meaning of many parameters in a single scenario in the scenarios folder?

### ISSUE THREAD

**Issue by GeneralMak** [carla-simulator/scenario_runner#781]
I am a new user of Carla,I want to create some new scenarios like the scenarios in the scenarios folder,not a single scenario but a combination of multiple.For example a combination of car following_leading_vehicle and No_Signal_Junction

**Comment by fabianoboril** [comment]
For new scenarios, I recommend to use OpenSCENARIO and our graphical editor: https://github.com/carla-simulator/traffic-generation-editor

**Comment by GeneralMak** [comment]
@fabianoboril  Thank you!,I will try
