### ISSUE TITLE
Module Not Found error : srunner module not found

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/scenario_runner#792]
i am new to CARLA . iam trying to run the scenario examples using OpenSCENARIO. when i run the python scripts in the scenario folder like 

python follow_leading_vehicle.py
I am receiving the follwoign error:

Traceback (most recent call last):
  File "follow_leading_vehicle.py", line 25, in <module>
    from srunner.scenariomanager.carla_data_provider import CarlaDataProvider
ModuleNotFoundError: No module named 'srunner'

I have CARLA simulator open, xosc file running. Kindly let me know what is expected from my side

Desktop (please complete the following information):

    OS: [Ubuntu 18.04]
    CARLA Version [CARLA 0.9.10.1]
    Python version 2.7]
    Scenario runner Version [0.9.10]

**Comment by glopezdiest** [comment]
Hey @werewolfdev, have you added the path to the ScenarioRunner folder onto the PYTHONPATH environment variable? It seems like it isn't finding that folder

**Comment by werewolfdev** [comment]
Hi @glopezdiest thanks for the quick reply. I added it to PYTHONPATH now and the error is gone . However now upon running the python scripts in the scenario folder like

python follow_leading_vehicle.py
 nothing happens , no error as well as no screen is opened. It just returns to next terminal command line. Thanks in advance

**Comment by werewolfdev** [comment]
Hi @glopezdiest  yes you were right . I just added the scenario runner path to the PYTHONPATH and it worked. thanks a lot
