### ISSUE TITLE
Scenario Runner: unable to attach actor: parent actor not found

### ISSUE THREAD

**Issue by Bedoubleu** [carla-simulator/scenario_runner#798]
Hello Guys,

I'm pretty new to CARLA and Scenario Runner and I hope you can help me.
I've set up my own scenario on a custom map I also created myself. The scenario itself is an ego vehicle controlled with the WaypointFollower and a Walker who crosses a pedestrian crosswalk. When the walker recognises the ego vehicle, the walker should stop to prevent a collision with the ego vehicle. Test Criteria in my scenario is the CollisionTest.
In my .xml config File I created several types of the scenario with different speeds for the walker as well as the ego vehicle which I want to run one after another.

Now to the problem:
If I run the scenario with: _python scenario_runner.py  --scenario group:PedCrossing --reloadWorld --output_
everything works fine with the first two scenarios. "_-All scenario tests were passed successfully!_" is the output I get.

When it comes to the third scenario i get the following Error message: 
<img width="1030" alt="SR_Error" src="https://user-images.githubusercontent.com/81804213/133296478-e84c9fb5-e07d-447c-a5c1-4658bb5bf04d.png">

As far as I understand, the collision sensor is the actor that should be connected to the parent, which is the ego vehicle. Please correct me if I'm wrong.
I don't get why it works for the first two scenarios and then suddenly throws the error.

At the moment I'm really clueless how to solve this problem. I hope you can help me to solve this issue.

 - OS: Ubuntu 20.04
 - CARLA Version: 0.9.11
 - Scenario Runner Version: 0.9.11
 - Python Version: 3.8.5

**Comment by fabianoboril** [comment]
@glopezdiest Can you look into this?

**Comment by glopezdiest** [comment]
That generally tends to happen when you try to attach a sensor to an actor that isn't there, meaning there might have been an error when spawning the actor. Can you make sure that the actor is there before trying to attach the sensor? Probably your initial position makes the actor collide with something (normally the ground). Could you check that?

**Comment by Bedoubleu** [comment]
First of all thanks for the reply. 

I tried setting the _criteria_enable=False_ in my "def __init__" to see what is happening. When I do this the first two scenarios work fine again and for the third I get the following output: _srunner.scenariomanager.carla_data_provider.get_location: Actor(id=191, type=vehicle.lincoln.mkz2017) not found!_
What's interesting about this, is that the vehicle is spawned on the map though.

I tried to debug my scenario to find out where the problem is. It seems the scenario_manager.py file calls "self.cleanup()" in the function "def run_scenario(self)" which then calls the "CarlaDataProvider.cleanup()"
<img width="698" alt="Bildschirmfoto 2021-09-21 um 15 08 15" src="https://user-images.githubusercontent.com/81804213/134176067-a4378e1c-b45a-4807-a744-a43701f1376b.png">
In there I added two print() commands to see if this batch is executed.

In the screenshot below you can see that it is only executed for the first scenario. For me it seems that the ego vehicle gets deleted and not set again for the next scenario, even though it is spawned on the map. But I'm not a 100% sure if I am on the right track here. 
<img width="907" alt="Bildschirmfoto 2021-09-21 um 15 13 37" src="https://user-images.githubusercontent.com/81804213/134177084-e33792c4-432c-4480-8e0a-b2c1c7e2e047.png">

**Comment by glopezdiest** [comment]
That's interesting. From what you told me, you are having the [*The scenario cannot be loaded*](https://github.com/carla-simulator/scenario_runner/blob/master/scenario_runner.py#L398) message. Could you check whether or not the ego vehicle has been properly assigned. [This function](https://github.com/carla-simulator/scenario_runner/blob/master/scenario_runner.py#L379) handles the spawn of the ego, can you check that *self.ego_vehicles* is not empty, None, or something similar? If something happened with the ego, and it is your only actor, the lack of the cleanup messages could make sense.

**Comment by Bedoubleu** [comment]
Yes exactly, _The scenario cannot be loaded_ pops up when scenario 3 tries to start.
I checked _self.ego_vehicles_ and it is not empty. But because of the fact that the ego vehicle doesn't get destroyed after scenario 2, I've got two ego_vehicles for scenario 3. as shown in the screenshot below.
<img width="890" alt="Bildschirmfoto 2021-09-23 um 14 34 39" src="https://user-images.githubusercontent.com/81804213/134507666-13450f05-6108-4680-8449-382361e533ca.png">

**Comment by glopezdiest** [comment]
Okay, so for some reason, the SR cleanup isn't being triggered during the second scenario, which breaks the third. Hmmm, I'll check see if I can reproduce it and report back. In the meantime, I suggest you manually check all cleanup calls and see whether or not they are being called

**Comment by glopezdiest** [comment]
Apparently, it was a bug we introduced after some changes to how the cleanup worked. The (one line) PR above should fix it. Please give it a try, see if it works for you

**Comment by Bedoubleu** [comment]
I added the line and now it is working perfectly fine!
Thank you guys. Appreciate your help!

**Comment by FADEAWAY114** [comment]
> I added the line and now it is working perfectly fine! Thank you guys. Appreciate your help!

Hello, I also got the same error, which line of code was added?
