### ISSUE TITLE
Missing support for FollowTrajectoryAction

### ISSUE THREAD

**Issue by Briandez** [carla-simulator/scenario_runner#803]
https://github.com/carla-simulator/scenario_runner/blob/05a811a6248c8033e4c76185ff40ae5eccad7e69/srunner/tools/openscenario_parser.py#L1211

Any plans for supporting FollowTrajectoryAction?

**Comment by glopezdiest** [comment]
Hey @Briandez, we have PR #751 with the very basic implementation, and it'll be merged soon. The rest of the action has no specific plans, but it'll come eventually

**Comment by Briandez** [comment]
Hi @glopezdiest 

I also did something couple of days ago similar to the PR

![image](https://user-images.githubusercontent.com/51113607/134469917-c1e863bf-2acb-459a-a2ff-1a4e1935828c.png)

      
But somehow i am getting this error on running the scenario:

![image](https://user-images.githubusercontent.com/51113607/134470187-6fd8c047-ef10-4f68-91b8-2d1599e3dc62.png)


But i guess this has something to do with the opendrive itself rather then the implementation but im not sure though.

**Comment by glopezdiest** [comment]
How are you passing that trajectory to the actor? Which behavior are you using? Some OSC behaviors modify the actor control, so you need to first create a controller before using those, or the error you are seeing might happen

**Comment by glopezdiest** [comment]
Closing this issue while waiting for the original poster to provide more information. Feel free to reopen it if needed
