### ISSUE TITLE
'TimeOut' object has no attribute 'optional'

### ISSUE THREAD

**Issue by clairebb1005** [carla-simulator/scenario_runner#804]
Hello,

I'm currently running the scenario_runner with openscenario files created by the traffic generation editor. 
But the same error keeps happening..

Error : 
> Traceback (most recent call last):
>   File "scenario_runner.py", line 408, in _load_and_run_scenario
>     self._analyze_scenario(config)
>   File "scenario_runner.py", line 259, in _analyze_scenario
>     if not self.manager.analyze_scenario(self._args.output, filename, junit_filename, json_filename):
>   File "C:\Users\Desktop\scenario_runner-0.9.11\scenario_runner-0.9.11\srunner\scenariomanager\scenario_manager.py", line 216, in analyze_scenario
>     if (not criterion.optional and
> AttributeError: 'TimeOut' object has no attribute 'optional'
> 'TimeOut' object has no attribute 'optional'
> No more scenarios .... Exiting

Any idea how to solve this problem? Thanks:)

 - OS: Windows 10
 - CARLA Version [0.9.11]
 - Scenario_Runner Version [0.9.11]
 - Python version [3.7]

**Comment by fabianoboril** [comment]
Hi,
can you switch to 0.9.11 branch (not tag) of scenario runner? This should resolve this issue.

**Comment by clairebb1005** [comment]
ok thanks! solved
