### ISSUE TITLE
Running Scenarios

### ISSUE THREAD

**Issue by joluko** [carla-simulator/scenario_runner#813]
Hello,
first of all i am new to Carla and scenario_runner. 

When I try to launch the example scenario FollowLeadingVehicle with >python scenario_runner.py --scenario FollowLeadingVehicle --reloadWorld the following message appears: 

_'Configuration for scenario FollowLeadingVehicle cannot be found!
No more scenarios .... Exiting'_

When trying to show the supported Scenarios with >python scenario_runner.py --list the list is empty:

_'Currently the following scenarios are supported:'_

**I would be very happy about any kind of help.**

EDIT:
The manual_control.py keeps printing:

_'Waiting for the ego vehicle...'_

 - OS: Windows 10 Enterprise
 - CARLA Version 0.9.11
 - Python version 3.7
 - Version 0.9.11

**Comment by fabianoboril** [comment]
Hi,
I am not familiar with windows, so we might need to go through this together.
It seems that somehow ScenarioRunner is not able to find the scenario files in your case. Therefore, can you please check what 
https://github.com/carla-simulator/scenario_runner/blob/8ed24c8da79d27dfbfd7fe00c12802eaf25f8b20/srunner/tools/scenario_parser.py#L108
this line provides in your case? Is this path valid, is it listing anything?
