### ISSUE TITLE
scenario_runner import carla error, No module named 'carla'

### ISSUE THREAD

**Issue by alibukharai** [carla-simulator/scenario_runner#820]
**Describe our question or idea**
Hello, I am new to CARLA Scenario Runner 
I downloaded the Scenario_runner 0.9.12 as compatible with Carla 0.9.12, I set the environment variable as shown in the figure attached but whenever I try to run a scenario by command (py -3.7 scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld), or (python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld) or (python3 scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld) it gives me an error related to import Carla. Anyone help me with this Thanks 
I also share my path to carla details:\
Carla is save in: D:\Carla\new\WindowsNoEditor
Scenario_runner is save in: D:\Carla\new\WindowsNoEditor\scenario_runner-0.9.12

you may approach me through email: alibukharai12@gmail.com

 - OS: [e.g. windows 10]
 - CARLA Version [e.g. CARLA 0.9.12]
 - Python version [e.g. 3.7]

[
![image](https://user-images.githubusercontent.com/60029742/136669022-5d872567-4b41-40ee-af3a-124ab83315d8.png)
![image](https://user-images.githubusercontent.com/60029742/136668732-bf10b505-3bd2-4b0d-9f8f-a35117a3b6b7.png)

![image](https://user-images.githubusercontent.com/60029742/136669198-803927d4-5dce-4c46-ab4f-a29357662564.png)
]

**Comment by glopezdiest** [comment]
@alibukharai You have to add those variables (CARLA_ROOT, SCENARIO_RUNNER_ROOT, PYTHONPATH) as fixed environment variables or you will have to set them up everytime you open a new terminal
