### ISSUE TITLE
Doc for creating new scenario is outdated

### ISSUE THREAD

**Issue by nda97531** [carla-simulator/scenario_runner#851]
I'm following the guide to create a new scenario but _[Docs/creating_new_scenario.md](https://github.com/carla-simulator/scenario_runner/blob/master/Docs/creating_new_scenario.md)_ seems to be outdated, I cannot find _atomic_scenario_behavior.py_ and _setup_vehicle()_ in _basic_scenario.py_.
Can someone please update it, thanks.

**Comment by glopezdiest** [comment]
They are indeed outdated, and some function names have been changed over time. We have plans to change it but the amount of documentation that needs updating is quite large, so we are working on it
