### ISSUE TITLE
OpenScenario Camera

### ISSUE THREAD

**Issue by steki555** [carla-simulator/scenario_runner#853]
Hello! I would like to get the results of the camera attached to my ego_vehicle.

I have already added the following code to my xosc file.
``
![image](https://user-images.githubusercontent.com/36483060/148612277-7ad3681c-dfdf-454c-9b26-5ca3da1490ce.png)

How can I receive Camera Data and LIDAR Data to later evaluate? For example as JPG or PNG ?
Thank you in advance!

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.12]
 - Python version [e.g. 3.7]
 - Version [e.g. 0.9.12]

**Comment by glopezdiest** [comment]
Hey @steki555. I've never trying using it but according to the code, [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/visualizer.py#L81) is the moment when the video is created and [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/visualizer.py#L130) is where each image is saved (per frame). Have you tried searching for that file?

**Comment by steki555** [comment]
Hey @glopezdiest ! Thank you for your answer! I've tried searching for it, but unfortunately I don't have such files neither in scenario_runner nor somewhere by my xosc. files. Should i maybe have something else set in order to trigger those methods? Or maybe I should make my own object of the class Visualiser? Or maybe the XOSC ControllerAction should have some other value set to true?
 When i start the scenario, I  see the camera from ego_vehicle PoV and also from birds eye PoV.

**Comment by glopezdiest** [comment]
Ah, apparently, that flag is always False. You can either change is [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/visualizer.py#L54), or modify the class to accept a new parameter.

@fabianoboril Do you have any more insights on this? I've never used this so I'm not sure what is its purpose. Can we add a new parameter to control this video writing?

**Comment by steki555** [comment]
Thank you for your answer! It helped a lot and now I can also see the video after setting the flag to True. Do you maybe also have experience with LIDAR Data?

**Comment by glopezdiest** [comment]
> Do you maybe also have experience with LIDAR Data?

What do you mean, visualizing the LIDAR as an image? If that's the case. I don't think there really is anything prepared for that in our examples. You can check [this function at the manual control](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py#L1132) that, each tick, parses the LIDAR data into an image (you only really care about the LIDAR conditional).
