### ISSUE TITLE
I tried to run manual_contro.py in scenario runner and I am getting this error "    from examples.manual_control import (World, HUD, KeyboardControl, CameraManager, ModuleNotFoundError: No module named 'examples'

### ISSUE THREAD

**Issue by umlautsim** [carla-simulator/scenario_runner#856]
I am able to run "python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld" succesfully but when I try to run the manual_control I get this no module error. I have added the python paths as directed in the getting started page.

`export UE4_ROOT=~/UnrealEngine_4.26 
export CARLA_ROOT=/home/*username*/carla
export SCENARIO_RUNNER_ROOT=/home/*username*/scenario_runner
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.12-py3.6-linux-x86_64.egg
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/agents`

**Comment by Kron610** [comment]
Try to add "export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/examples"

**Comment by glopezdiest** [comment]
As a follow up to what Kron610 said, we recently removed that dependency ([this is the commit](https://github.com/carla-simulator/scenario_runner/commit/06d912b78a34522795b7c2b290c693e34b3ba6a4), as it wasn't really a good idea to begin with.

**Comment by LucasFKobernic** [comment]
Hi @glopezdiest 

I'm facing the same issue. I am on windows and after a added:

set PYTHONPATH=%PYTHONPATH%;%CARLA_ROOT%\PythonAPI\examples\

The error persists. Any idea what is causing the issue? I'm usgin Scenario Runner 0.9.12

**Comment by umlautsim** [comment]
HI @LucasFKobernic, I am facing the same error. Did you find any fix?. Thanks
