### ISSUE TITLE
Possible Bug: Ego vehicle not able to make use of SpeedActionDynamics when under simple_vehicle_control using openSCENARIO scenario generation

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/scenario_runner#875]
Hi team, Iam trying to create scenarios using openSCENARIO scripts. I am trying to create a simple scenario where the ego_ vehicle is controlled by simple_vehicle_control and made to move from 0kmph to 20 kmph in with SpeedDynamics linear . I also tried with other Shapes . However all the time the speed value just shoots up from 0 to 20kmph . I would like to have a linear or stepwise transition for the speed parameter of my ego vehicle. Could anyone let me know what I myt be  missing out : The respective SpeedAction code segment :
```
<SpeedAction>
                      <SpeedActionDynamics dynamicsShape="linear" value="50" dynamicsDimension="distance"/>
                      <SpeedActionTarget>
                        <AbsoluteTargetSpeed value="5.0"/>
                      </SpeedActionTarget>
                    </SpeedAction>
```
It works for actors run as simulation but not for ego_vehicle

 - OS: [e.g. Ubuntu 18.04]
 - CARLA Version [e.g. CARLA 0.9.13]
 - Python version [e.g. 3.6]
 - Version [e.g. 0.9.13]

**Comment by werewolfdev** [comment]
@fabianoboril  Hi Could you please provide your insights on the same. Thanks

**Comment by glopezdiest** [comment]
Hey @werewolfdev. Your SpeedAction code seems fine, could provide the whole script you are using to reproduce the erros? As well as how are you calling scenario runner.

**Comment by werewolfdev** [comment]
Hey @glopezdiest  thanks a lot for the reply. The xosc script is as below.  Iam running the scenario using scenario_runner script normally from the scenario runner folder of CARLA repository liek below:
python3.6 scenario_runner.py --openscenario /home/schemba/CARLA_0.9.13/carla/scenario_runner-0.9.13/srunner/examples/Abbiege_FRTest.xosc


`<?xml version="1.0" ?>
<OpenSCENARIO>
    <FileHeader author="QGIS OSCGenerator Plugin" date="2021-09-22T14:40:12" description="Generated OpenSCENARIO File" revMajor="1" revMinor="0"/>
    <ParameterDeclarations/>
    <CatalogLocations/>
    <RoadNetwork>
        <LogicFile filepath="Town01"/>
        <SceneGraphFile filepath=""/>
    </RoadNetwork>
    <Entities>
        <ScenarioObject name="hero">
            <Vehicle name="vehicle.tesla.model3" vehicleCategory="car">
                <ParameterDeclarations/>
                <Performance maxAcceleration="200" maxDeceleration="10.0" maxSpeed="69.444"/>
                <BoundingBox>
                    <Center x="1.5" y="0.0" z="0.9"/>
                    <Dimensions height="1.8" length="4.5" width="2.1"/>
                </BoundingBox>
                <Axles>
                    <FrontAxle maxSteering="0.5" positionX="3.1" positionZ="0.3" trackWidth="1.8" wheelDiameter="0.6"/>
                    <RearAxle maxSteering="0.0" positionX="0.0" positionZ="0.3" trackWidth="1.8" wheelDiameter="0.6"/>
                </Axles>
                <Properties>
                    <Property name="type" value="ego_vehicle"/>
                </Properties>
            </Vehicle>
        </ScenarioObject>
        <ScenarioObject name="Vehicle_1">
            <Vehicle name="vehicle.audi.tt" vehicleCategory="car">
                <ParameterDeclarations/>
                <Performance maxAcceleration="200" maxDeceleration="10.0" maxSpeed="69.444"/>
                <BoundingBox>
                    <Center x="1.5" y="0.0" z="0.9"/>
                    <Dimensions height="1.8" length="4.5" width="2.1"/>
                </BoundingBox>
                <Axles>
                    <FrontAxle maxSteering="0.5" positionX="3.1" positionZ="0.3" trackWidth="1.8" wheelDiameter="0.6"/>
                    <RearAxle maxSteering="0.0" positionX="0.0" positionZ="0.3" trackWidth="1.8" wheelDiameter="0.6"/>
                </Axles>
                <Properties>
                    <Property name="type" value="simulation"/>
                </Properties>
            </Vehicle>
        </ScenarioObject>
    </Entities>
    <Storyboard>
        <Init>
            <Actions>
                <GlobalAction>
                    <EnvironmentAction>
                        <Environment name="Environment1">
                            <TimeOfDay animation="false" dateTime="2020-10-23T04:00:00"/>
                            <Weather cloudState="free">
                                <Sun azimuth="0" elevation="1.31" intensity="0.85"/>
                                <Fog visualRange="100000"/>
                                <Precipitation intensity="0" precipitationType="dry"/>
                            </Weather>
                            <RoadCondition frictionScaleFactor="1.0"/>
                        </Environment>
                    </EnvironmentAction>
                </GlobalAction>
                <Private entityRef="hero">
                    <PrivateAction>
                        <TeleportAction>
                            <Position>

                                <WorldPosition h="1.5709483394834305" p = "0" r = "0" x="92.32854315481438" y="-135.08543140104072" z="0.2"/>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
                    <PrivateAction>
                        <ControllerAction>
                            <AssignControllerAction>
                                <Controller name="HeroAgent_1">
                                    <Properties>
                                        <Property name="module" value="simple_vehicle_control"/>
                                        <Property name="attach_camera" value="true"/>
                                    </Properties>
                                </Controller>
                            </AssignControllerAction>
                            <OverrideControllerValueAction>
                                <Throttle active="false" value="0"/>
                                <Brake active="false" value="0"/>
                                <Clutch active="false" value="0"/>
                                <ParkingBrake active="false" value="0"/>
                                <SteeringWheel active="false" value="0"/>
                                <Gear active="false" number="0"/>
                            </OverrideControllerValueAction>
                        </ControllerAction>
                    </PrivateAction>
                </Private>
                <Private entityRef="Vehicle_1">
                    <PrivateAction>
                        <TeleportAction>
                            <Position>

                                <WorldPosition h="1.5709483394835726" x="93.32854315481438" y="-100.085" z="0.2"/>
                            </Position>
                        </TeleportAction>
                    </PrivateAction>
                    <PrivateAction>
                        <ControllerAction>
                            <AssignControllerAction>
                                <Controller name="VehicleAgent_1">
                                    <Properties>
                                        <Property name="module" value="simple_vehicle_control"/>
                                    </Properties>
                                </Controller>
                            </AssignControllerAction>
                            <OverrideControllerValueAction>
                                <Throttle active="false" value="0"/>
                                <Brake active="false" value="0"/>
                                <Clutch active="false" value="0"/>
                                <ParkingBrake active="false" value="0"/>
                                <SteeringWheel active="false" value="0"/>
                                <Gear active="false" number="0"/>
                            </OverrideControllerValueAction>
                        </ControllerAction>
                    </PrivateAction>
                    <PrivateAction>
                        <LongitudinalAction>
                            <SpeedAction>
                                <SpeedActionDynamics dynamicsDimension="distance" dynamicsShape="step" value="0.1"/>
                                <SpeedActionTarget>
                                    <AbsoluteTargetSpeed value="0"/>
                                </SpeedActionTarget>
                            </SpeedAction>
                        </LongitudinalAction>
                    </PrivateAction> 
                </Private>
            </Actions>
        </Init>
        <Story name="OSC Generated Story">
            <Act name="OSC Generated Act">
                <ManeuverGroup maximumExecutionCount="1" name="Maneuver group for Ego_1">
                    <Actors selectTriggeringEntities="false">
                        <EntityRef entityRef="hero"/>
                    </Actors>
                    <Maneuver name="Maneuver ID 2">
                        <Event name="Event Maneuver ID 2" priority="overwrite">
                            <Action name="Action for Manuever ID 2">
                                <PrivateAction>
                                  <LongitudinalAction>
                                    <SpeedAction>
                                      <SpeedActionDynamics dynamicsShape="step" value="1" dynamicsDimension="distance"/>
                                      <SpeedActionTarget>
                                        <AbsoluteTargetSpeed value="11.1111"/>
                                      </SpeedActionTarget>
                                    </SpeedAction>
                                  </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 2">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="0.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                        <Event name="SlowingDown" priority="overwrite">
                            <Action name="SlowingDown">
                                <PrivateAction>
                                  <LongitudinalAction>
                                    <SpeedAction>
                                      <SpeedActionDynamics dynamicsShape="linear" value="10" dynamicsDimension="time"/>
                                      <SpeedActionTarget>
                                        <AbsoluteTargetSpeed value="7.2222"/>
                                      </SpeedActionTarget>
                                    </SpeedAction>
                                  </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 2">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="10.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                        <Event name="ContinueSlow" priority="overwrite">
                            <Action name="ContinueSlow">
                                <PrivateAction>
                                    <LongitudinalAction>
                                      <SpeedAction>
                                        <SpeedActionDynamics dynamicsShape="step" value="20" dynamicsDimension="time"/>
                                        <SpeedActionTarget>
                                          <AbsoluteTargetSpeed value="7.2222"/>
                                        </SpeedActionTarget>
                                      </SpeedAction>
                                    </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 1">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="20.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                        <Event name="ContinueSlow" priority="overwrite">
                            <Action name="ContinueSlow">
                                <PrivateAction>
                                    <LongitudinalAction>
                                      <SpeedAction>
                                        <SpeedActionDynamics dynamicsShape="step" value="100" dynamicsDimension="time"/>
                                        <SpeedActionTarget>
                                          <AbsoluteTargetSpeed value="5.55556"/>
                                        </SpeedActionTarget>
                                      </SpeedAction>
                                    </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 1">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="20.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                                      <Condition name="StartConditionLeadingVehicleKeepsVelocity" delay="0" conditionEdge="rising">
                                                        <ByEntityCondition>
                                                          <TriggeringEntities triggeringEntitiesRule="any">
                                                            <EntityRef entityRef="Vehicle_1"/>
                                                          </TriggeringEntities>
                                                          <EntityCondition>
                                    
                                                            <RelativeDistanceCondition entityRef="hero" relativeDistanceType="cartesianDistance" value="21.0" freespace="true" rule="lessThan"/>
                                                          </EntityCondition>
                                                        </ByEntityCondition>
                                                      </Condition> 
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                    </Maneuver>
                </ManeuverGroup>
                <ManeuverGroup maximumExecutionCount="1" name="Maneuver group for Vehicle_1">
                    <Actors selectTriggeringEntities="false">
                        <EntityRef entityRef="Vehicle_1"/>
                    </Actors>
                    <Maneuver name="Maneuver ID 1">
                        <Event name="StartAdv" priority="overwrite">
                            <Action name="StartAdv">
                                <PrivateAction>
                                    <LongitudinalAction>
                                      <SpeedAction>
                                        <SpeedActionDynamics dynamicsShape="step" value="1" dynamicsDimension="distance"/>
                                        <SpeedActionTarget>
                                          <AbsoluteTargetSpeed value="11.1111"/>
                                        </SpeedActionTarget>
                                      </SpeedAction>
                                    </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 1">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="0.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                        <Event name="AdvSlowingDown" priority="overwrite">
                            <Action name="AdvSlowingDown">
                                <PrivateAction>
                                  <LongitudinalAction>
                                    <SpeedAction>
                                      <SpeedActionDynamics dynamicsShape="linear" value="10" dynamicsDimension="time"/>
                                      <SpeedActionTarget>
                                        <AbsoluteTargetSpeed value="2.77778"/>
                                      </SpeedActionTarget>
                                    </SpeedAction>
                                  </LongitudinalAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                    <Condition conditionEdge="rising" delay="0" name="Condition for Maneuver ID 2">
                                        <ByValueCondition>
                                            <SimulationTimeCondition rule="greaterThan" value="10.0"/>
                                        </ByValueCondition>
                                    </Condition>
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                        <Event name="AdvTurns" priority="overwrite">
                            <Action name="AdvTurns">
                                <PrivateAction>
                                    <RoutingAction>
                                        <AssignRouteAction>
                                            <Route closed="false" name="OSC Generated Route">
                                                <Waypoint routeStrategy="fastest">
                                                    <Position>
                                                        <WorldPosition x="101" y="-59.8" z="0" h="0"/>
                                                    </Position>
                                                </Waypoint>
                                                <Waypoint routeStrategy="fastest">
                                                    <Position>
                                                        <WorldPosition x="111.6" y="-59.4" z="0" h="0"/>
                                                    </Position>
                                                </Waypoint>
                                                <Waypoint routeStrategy="fastest">
                                                    <Position>
                                                        <WorldPosition x="131.7" y="-59.3" z="0" h="0"/>
                                                    </Position>
                                                </Waypoint>
                                                <Waypoint routeStrategy="fastest">
                                                    <Position>
                                                        <WorldPosition x="140" y="-59.3" z="0" h="0"/>
                                                    </Position>
                                                </Waypoint>
                                            </Route>
                                        </AssignRouteAction>
                                    </RoutingAction>
                                </PrivateAction>
                            </Action>
                            <StartTrigger>
                                <ConditionGroup>
                                                   <Condition name="StartConditionLeadingVehicleKeepsVelocity" delay="0" conditionEdge="rising">
                                                     <ByEntityCondition>
                                                       <TriggeringEntities triggeringEntitiesRule="any">
                                                         <EntityRef entityRef="hero"/>
                                                       </TriggeringEntities>
                                                       <EntityCondition>
                                 
                                                         <RelativeDistanceCondition entityRef="Vehicle_1" relativeDistanceType="longitudinal" value="21.0" freespace="true" rule="lessThan"/>
                                                       </EntityCondition>
                                                     </ByEntityCondition>
                                                   </Condition>   
                                </ConditionGroup>
                            </StartTrigger>
                        </Event>
                    </Maneuver>
                </ManeuverGroup>
                <StartTrigger>
                    <ConditionGroup>
                        <Condition conditionEdge="rising" delay="0" name="StartTime">
                            <ByValueCondition>
                                <SimulationTimeCondition rule="equalTo" value="0"/>
                            </ByValueCondition>
                        </Condition>
                    </ConditionGroup>
                </StartTrigger>
                <StopTrigger>
                    <ConditionGroup>
                        <Condition conditionEdge="rising" delay="0" name="EndCondition">
                            <ByValueCondition>
                                <SimulationTimeCondition rule="equalTo" value="10000"/>
                            </ByValueCondition>
                        </Condition>
                    </ConditionGroup>
                </StopTrigger>
            </Act>
        </Story>
        <StopTrigger>
            <ConditionGroup>
                <Condition name="criteria_DrivenDistanceTest" delay="0" conditionEdge="rising">
                    <ByValueCondition>
                        <ParameterCondition parameterRef="distance_success" value="100" rule="lessThan"/>
                    </ByValueCondition>
                </Condition>
            </ConditionGroup>
        </StopTrigger>
    </Storyboard>
</OpenSCENARIO>
`

**Comment by glopezdiest** [comment]
Great, I'll test it ASAP. Feel free to remind me if I haven't said anything by next week

**Comment by werewolfdev** [comment]
Thanks .sounds good .Yeah surely will remind you 😂😂😂

**Comment by glopezdiest** [comment]
> It works for actors run as simulation but not for ego_vehicle
 
Hey @werewolfdev, from what I can see, neither the ego nor the other actor does change speed linearly. The issue you are seeing is caused by a series of factors.

First of all, when you run the *.xosc*, we get the xml file and parse it with the [OpenScenarioParser](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/tools/openscenario_parser.py). For the `SpeedAction` specifically, this is done [here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/tools/openscenario_parser.py#L1175), and as you can see, **we are not parsing the dynamic shape**, so ScenarioRunner doesn't know that's what you want.

From there, we call the [ChangeActorTargetSpeed](https://github.com/carla-simulator/scenario_runner/blob/f4d00d88eda4212a1e119515c96281a4be5c234e/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L408), which tells the vehicle's controller that the target speed has changed (unexpected, I know). In your case, you are using the [SimpleVehicleControl](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/simple_vehicle_control.py), which moves the vehicle not with physics, but by forcing its speed ([here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/simple_vehicle_control.py#L309)). As such, it is capable of instantly changing the speed, so that's what it does.

As for the solution, it's a bit tricky. We should definitely add the parsing of the dynamic shape. In the meantine, you can check the [NPCVehicleControl](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py), which actually uses physics to move the vehicle, so the linear shape will be done. BUT, the step won't (as it is now bound by physics) so you'll have to mix the two controllers together.

**Comment by werewolfdev** [comment]
Hey @glopezdiest . Thanks a lot for the reply. Hope the community could add this feature soon. Regarding the solution , I can change the type of module to npc_vehicle_control for the ego vehicle: Actually I need just the linear speed changes and not the step dynamics now, to generate the required scenarios. So as per your views, just changing the type of control to npc_vehicle_control will do the trick for me. I will try it out and let you know son. Please correct me if Iam wrong

**Comment by glopezdiest** [comment]
Correct, you need:
- NPCVehicleControl for the the linear shape
- SimpleVehicleControl for the the step shape
If you just need one shape, just use that specific controller

**Comment by werewolfdev** [comment]
@glopezdiest Thanks. So i have change controller as npc_vehicle_control in xosc script but then when i run it , no window opens like simple_vehicle_control. In npc_vehicle_control is there any additional code I should run to run the simulation or everything same as in simple_vehicle_control. I would actually like to run the ego vehicle also like simulation and not from key pad. Thanks

**Comment by glopezdiest** [comment]
Oh yeah that's true, the simple_vehicle_control does open a window, which other controllers don't. You'd have to integrate it :slightly_smiling_face:. 

>  I would actually like to run the ego vehicle also like simulation and not from key pad

Can't you use the npc_vehicle_control with the ego to not move it with the key pad?

**Comment by werewolfdev** [comment]
oh is it. Yeah Iam using npc . I hope i just need to integrate that window opening .Ok i would look into the simple_vehicle_control script and see how to integrate this. I hope thats where I have to look into. I will update you soon

**Comment by werewolfdev** [comment]
Hi @glopezdiest I integrated visualizer into npc vehicle control script and tested the control action of linear SpeedActionDynamics. It works. Thanks a lot for your help.
