### ISSUE TITLE
Why the autopilot in manual_control  doesn't work？

### ISSUE THREAD

**Issue by Georgezxh** [carla-simulator/scenario_runner#890]
I run the command “python3 scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld”，
 and then run the manual_control.py. I want the ego vehicle auto-driving, so I enter P in keyboard to change to autopilot mode, but it doesn't work, the ego vehicle doesn't move. 

I need help about how can I make the ego vehicle auto-driving in the scenarios

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - CARLA 0.9.10
 - Python 3.8
 - Version0.9.10

**Comment by DriveSlowly** [comment]
I have the same confusion,  the ego car should follow the leading car, but the ego car need manual control by keybord input (WASD). do you solved your problem now, how can the ego car automaticallu follows the leading car?
