### ISSUE TITLE
ModuleNotFoundError: No module named 'agents'

### ISSUE THREAD

**Issue by chenhengwei1999** [carla-simulator/scenario_runner#896]
I want to use scenario runner in Carla simulator. I follow the tutorial on the official website(Calra-Simulator:https://carla.readthedocs.io/en/latest/start_quickstart/ ,Scenario-Runner:https://carla-scenariorunner.readthedocs.io/en/latest/getting_scenariorunner/) and have installed package version carla-0.9.13. Then I need to find the corresponding version of scenario runner.

But I can't find the corresponding non-source download package in scenario, as shown in the figure below. I can only find the source version(This will conflict with my package version of Carla). 
![image](https://user-images.githubusercontent.com/63592913/168998269-b9bc7314-e55c-47e7-8a34-c9bc1ff72657.png)

So I can only download the source version of scenario runner(*.tar.gz), but the following errors occur at runtime.
![image](https://user-images.githubusercontent.com/63592913/168999502-1fe9759f-d06e-4ab3-91c2-3b083ea6413b.png)

In order to check the errors, I tried to import the agents package in conda environment, but the same error occurred. Does Carla of 0.9.13 package need to download the agents package separately to run scenario runner? as shown in the figure below
![image](https://user-images.githubusercontent.com/63592913/169000442-a1d3ada6-c5be-4db2-8ed7-a70b67140718.png)

How do I check for errors? Thank you in advance!

**[update][update][update]**
Guided by this question(https://github.com/carla-simulator/scenario_runner/issues/81), I added ...carla/PythonAPI/carla to the PYTHONPATH path. I can successfully run the command < Python scenario_ runner. py --scenario FollowLeadingVehicle_ 1 -- reloadworld >. I want to make sure this is the right thing to do？ Look forward to your answers. Thank you very much

Hope to get help, thank you！

**Desktop  information:**
 - OS: [e.g. Ubuntu 20.04]
 - CARLA Version [e.g. CARLA 0.9.13]
 - Python version [e.g. 3.7]
 - Scenario Runner Version [e.g. 0.9.13]

**Comment by vimal4353** [comment]
Please set the carla agents folder path in atomic_behavior.py file

**Comment by chenhengwei1999** [comment]
> Please install pip install agents and set the carla agents folder path in atomic_behavior.py file

Thanks for you reply. I tried add the PYTHONPATH=.../path/to/carla/root/PythonAPI/carla into the ~/.bashrc file.
So the <agents> python thrid library can be imported successfully.

By the way, I could't find the location where atomic_behavior.py exits. What is the functionality of the file? If possible, could you please give me some details about it, such as why i need to use it(I am a new Carla-er, and i am not familar with the simulator, please give me more patience, THANKS).

I am using the carla-0.9.13 and ubuntu 20.04.

**Comment by vimal4353** [comment]
You can set the path in C:\Users\Admin\carla\PythonAPI\scenario_runner-0.9.11\srunner\scenariomanager\scenarioatomics\atomic_behaviors.py

sys.path.insert(0,'C:/Users/Admin/carla/PythonAPI/carla')    -   put before importing the agents module

**Comment by chenhengwei1999** [comment]
> You can set the path in C:\Users\Admin\carla\PythonAPI\scenario_runner-0.9.11\srunner\scenariomanager\scenarioatomics\atomic_behaviors.py
> 
> sys.path.insert(0,'C:/Users/Admin/carla/PythonAPI/carla') - put before importing the agents module

Thank you very much for your advice.

**Comment by glopezdiest** [comment]
@chenhengwei1999 Others have said it already, but the agents folder has to be added to the PYTHONPATH in order to be used, as seen [here](https://carla-scenariorunner.readthedocs.io/en/latest/getting_scenariorunner/#update-from-source), from there, just import the agents folder in python ([an example](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L33)).

Closing this issue as it seems resolved, but feel free to reopen it if you still have issues
