### ISSUE TITLE
Configuration for Scenario Error:

### ISSUE THREAD

**Issue by laks1806** [carla-simulator/scenario_runner#919]
@fabianoboril, I tried changing the path and everything seems correct but this error keeps coming : 
```
python scenario_runner.py --scenario FollowLeadingVehicle_1 --reloadWorld
Configuration for scenario FollowLeadingVehicle_1 cannot be found!
No more scenarios .... Exiting
```
my python path is: 
`/opt/carla-simulator/PythonAPI/carla/dist/carla-0.9.11-py2.7-linux-x86_64.egg:/opt/carla-simulator/PythonAPI/carla/agents:/opt/carla-simulator/PythonAPI/carla`

_Originally posted by @laks1806 in https://github.com/carla-simulator/scenario_runner/issues/311#issuecomment-1180375753_

**Comment by wkgud9090** [comment]
have same problem

**Comment by ghazalmatt3r** [comment]
Same here

**Comment by glopezdiest** [comment]
As @ghazalmatt3r said, you should have an environment variable pointin to your Scenario runner folder for the configurations to be found. Closing the issue as it is resolved, but feel free to reopen it if needed
