### ISSUE TITLE
TypeError: setup() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by nadrainam** [carla-simulator/scenario_runner#925]
Hi
I am trying to run the Slalom.xosc scenario for CARLA scenario runner by using the command ( python scenario_runner.py --openscenario srunner/examples/Slalom.xosc). However, when i run the command i got the following error

The scenario cannot be loaded
Traceback (most recent call last):
  File "scenario_runner.py", line 466, in _load_and_run_scenario
    timeout=100000)
  File "/home/nadra/scenario_runner/srunner/scenarios/open_scenario.py", line 189, in __init__
    terminate_on_failure=False, criteria_enable=criteria_enable)
  File "/home/nadra/scenario_runner/srunner/scenarios/basic_scenario.py", line 126, in __init__
    self.scenario = Scenario(behavior_seq, criteria, self.name, self.timeout, self.terminate_on_failure)
  File "/home/nadra/scenario_runner/srunner/scenarios/basic_scenario.py", line 303, in __init__
    self.scenario_tree.setup(timeout=1)
TypeError: setup() got an unexpected keyword argument 'timeout'
exception setup() got an unexpected keyword argument 'timeout'

i am not understanding what is the problem. I have checked the requirements in the requirement file and all the python packages are according to the given requirement. 
my carla version is 0.9.11

Best Regards

**Comment by glopezdiest** [comment]
Hello @nadrainam, as this seems to be related to *py_trees*, what version of *py_trees* are you using? scenario runner requires version 0.8.3
