### ISSUE TITLE
openscenario_parse.py don't supports parameter which is scientific notation (for example, 1.234+e+01)

### ISSUE THREAD

**Issue by fukuchi0105** [carla-simulator/scenario_runner#927]
**Describe the bug**
In "openscenario_parse.py", "is_literal function" don't support scientific notation (for example, 1.234+e+01). Therefore, when parsing OpenSCENARIO file which include scientific notations parameter, it cannot parse it.

current parser of regular expression: r"(-)?\d+(\.\d)?"
proposed parser of regular expression: r"(-)?\d+(\.\d)?((e|E)(\+|-)\d+)?"

**To Reproduce**
1. make OpenSCENARIO file which include scientific notations
2. run scnario_runner by using above OpenSCENARIO file

**Expected behavior**
Be able to run scenario by using OpenSCENARIO file including scientific notations

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CARLA 0.9.13
 - Python version 3.9
 - Version 0.9.13

**Comment by golnazraja** [comment]
I also faced the same issue and fixed it with adding support of parsing parameters with scientific notation.

Here is link to my pull request: https://github.com/carla-simulator/scenario_runner/pull/1023
