### ISSUE TITLE
Hello, may I ask if the currently unsupported OpenScenario tag is because Carla does not support it

### ISSUE THREAD

**Issue by xibei312** [carla-simulator/scenario_runner#931]
**Describe our question or idea**
A clear and concise description.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - CARLA Version [CARLA 0.9.12]
 - Python version [3.8]
 - Version [0.9.12]

**Comment by glopezdiest** [comment]
Not sure what you mean exactly, but yes, by definition, unsupported means that it is not supported. 

Currently, Scenario Runner only provides partial support for OpenScenario 1.0, and while the majority of the actions are supported, any action with the unsupported tag is indeed not supported
