### ISSUE TITLE
The CARLA server uses the wrong map

### ISSUE THREAD

**Issue by gabrik** [carla-simulator/scenario_runner#936]
**Describe our question or idea**
Hi, I just installed CARLA 0.9.13 and tried to use the scenario runner to spawn a simple FreeRide scenario
But I got this error:
```
$ python3 scenario_runner.py --scenario FreeRide_1 --timeout 100
The CARLA server uses the wrong map: Town10HD_Opt
This scenario requires to use map: Town01
No more scenarios .... Exiting
```
Do I need more maps?

**Expected behavior**
The scenario runner set-up the scenario

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CARLA CARLA 0.9.13
 - Python 3.6
 - Version 0.9.13

**Comment by glopezdiest** [comment]
In short, you are using the wrong map, and you have to manually change the map, or use the `--reloadWorld` argument.

Why? Scenarios start at a specific location at a specific map, which has to be given by the users. To ensure the correct behavior, Scenario Runner checks that the loaded map is the one the scenario needs and if not, the simulation stops, and you see the message you are reporting.
